# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'nokogiri'
require 'open-uri'

# page_1 = open("file:///Users/siobhanpmahoney/Desktop/medium-export/bookmarks/bookmarks-0001.html")
# page_1 = File.read("file:///Users/siobhanpmahoney/Desktop/medium-export/bookmarks/bookmarks-0001.html")

# @all_links = ["https://medium.com/p/async-generators-as-an-alternative-to-state-management-f9871390ffca",
#   "https://medium.com/p/using-modern-regexes-in-javascript-30322af557c5",
#   "https://medium.com/p/es6-set-map-weak-a2aeb7e2d384",
#   "https://medium.com/p/how-to-store-your-state-data-f17ceca37aa",
#   "https://medium.com/p/es2015-built-ins-part-1-symbols-sets-and-maps-608f126dd906",
#   "https://medium.com/p/reduce-filter-and-map-without-reduce-filter-and-map-787c21671c95",
#   "https://medium.com/p/array-vs-set-vs-map-vs-object-real-time-use-cases-in-javascript-es6-47ee3295329b",
#   "https://medium.com/p/performance-creating-map-object-create-null-d9265331f0d4",
#   "https://medium.com/p/writing-javascript-with-map-reduce-980602ff2f2f",
#   "https://medium.com/p/es2018-finally-method-in-native-promise-bb865834abba",
#   "https://medium.com/p/learn-understand-javascripts-map-function-ffc059264783",
#   "https://medium.com/p/es9-javascripts-state-of-art-in-2018-9a350643f29c",
#   "https://medium.com/p/javascript-whats-new-in-ecmascript-2018-es2018-17ede97f36d5",
#   "https://medium.com/p/es6-lets-divide-our-phones-into-classes-4574bd0454bf",
#   "https://medium.com/p/es6-cool-stuffs-a-new-js-string-with-template-literals-c23a8af11b2",
#   "https://medium.com/p/es6-cool-stuffs-destructuring-me-plz-b8f1335d241a",
#   "https://medium.com/p/es6-cool-stuffs-var-let-and-const-in-depth-24512e593268",
#   "https://medium.com/p/es6-magical-stuffs-spread-syntax-in-depth-afdd0118ebd0",
#   "https://medium.com/p/es6-set-vs-array-what-and-when-efc055655e1a",
#   "https://medium.com/p/javascript-learn-to-chain-map-filter-and-reduce-acd2d0562cd4",
#   "https://medium.com/p/es6-map-vs-object-what-and-when-b80621932373",
#   "https://medium.com/p/async-javascript-a-pocket-reference-2bb16ac40d21",
#   "https://medium.com/p/coding-dynamic-behavior-with-the-strategy-pattern-c0bebaee6671",
#   "https://medium.com/p/principles-of-component-api-prop-design-bb20cd58da54",
#   "https://medium.com/p/rethinking-unit-test-assertions-55f59358253f",
#   "https://medium.com/p/lets-clear-up-the-confusion-around-the-slice-splice-split-methods-in-javascript-8ba3266c29ae",
#   "https://medium.com/p/the-3-steps-in-an-empirical-approach-for-analyzing-the-run-time-of-algorithms-f48d90e18908",
#   "https://medium.com/p/what-i-learned-from-doing-1000-code-reviews-fe28d4d11c71",
#   "https://medium.com/p/50-data-structure-and-algorithms-interview-questions-for-programmers-b4b1ac61f5b0",
#   "https://medium.com/p/pocket-ceo-nate-weiner-explains-how-to-create-a-top-productivity-app-58f9b6cf76d9",
#   "https://medium.com/p/how-to-impress-interviewers-by-using-recursion-in-javascript-with-es6-features-a14c763110d7",
#   "https://medium.com/p/javascript-essentials-objects-56373a1a6bfb",
#   "https://medium.com/p/javascript-arrow-functions-how-why-when-and-when-not-to-use-them-fb8c2de9dbdc",
#   "https://medium.com/p/a-practical-es6-guide-on-how-to-perform-http-requests-using-the-fetch-api-594c3d91a547",
#   "https://medium.com/p/10-technical-interview-tips-67bf962efaa0",
#   "https://medium.com/p/coding-interviews-for-dummies-5e048933b82b",
#   "https://medium.com/p/cracking-the-frontend-coding-interview-ec7d5b1e6755",
#   "https://medium.com/p/testing-react-components-with-jest-and-enzyme-324a8684aad4",
#   "https://medium.com/p/learning-to-write-react-tests-on-example-of-react-tic-tac-toe-app-acf7ae2b94b8",
#   "https://medium.com/p/you-might-not-need-redux-be46360cf367",
#   "https://medium.com/p/redux-thunk-vs-redux-saga-93fe82878b2d",
#   "https://medium.com/p/how-to-not-suck-at-design-a-5-minute-guide-for-the-non-designer-291efac43037",
#   "https://medium.com/p/the-common-genius-of-lincoln-and-einstein-84595b688cbc",
#   "https://medium.com/p/react-redux-connect-when-and-how-to-use-it-f2a1edab2013",
#   "https://medium.com/p/javascript-essentials-types-data-structures-3ac039f9877b",
#   "https://medium.com/p/how-to-write-a-web-developer-r%C3%A9sum%C3%A9-that-will-help-you-get-an-interview-ee4fe95d9608",
#   "https://medium.com/p/rails-5-api-jwt-setup-in-minutes-using-devise-71670fd4ed03",
#   "https://medium.com/p/how-to-write-epic-unit-tests-with-typescript-jest-redux-and-rxjs-6-in-a-react-based-application-357497b2956a",
#   "https://medium.com/p/how-to-absolutely-ace-developer-presentations-ef12548729ae",
#   "https://medium.com/p/evolution-and-agile-b9f8f9f95924",
#   "https://medium.com/p/a-short-guide-to-static-and-dynamic-libraries-a52acf6f7904",
#   "https://medium.com/p/the-trick-to-thinking-clearer-and-better-4a61c54114fa",
#   "https://medium.com/p/how-to-master-any-skill-92287046f55b",
#   "https://medium.com/p/building-your-own-design-pattern-5f30b7d16122",
#   "https://medium.com/p/dockerizing-spas-9f72b7867e41",
#   "https://medium.com/p/5-easy-ways-to-make-your-ui-more-accessible-34a10522ae99",
#   "https://medium.com/p/ux-vs-ui-vs-ia-vs-ixd-4-confusing-digital-design-terms-explained-222f3bcc3255",
#   "https://medium.com/p/oh-mamma-im-in-love-with-gradient-c81943e3c92b",
#   "https://medium.com/p/increasing-the-adoption-of-ux-and-the-products-you-design-part-1-8871cf8368d6",
#   "https://medium.com/p/how-we-hire-front-end-engineers-at-the-new-york-times-e1294ea8e3f8",
#   "https://medium.com/p/web-application-security-understanding-the-browser-5305ed2f1dac",
#   "https://medium.com/p/mastering-react-functional-components-with-recompose-d4dd6ac98834",
#   "https://medium.com/p/focus-and-deep-work-your-secret-weapons-to-becoming-a-10x-developer-8e203a6ad291",
#   "https://medium.com/p/react-js-compound-components-a6e54b5c9992",
#   "https://medium.com/p/implementing-the-async-await-syntax-for-promise-request-javascript-c4a193827bd2",
#   "https://medium.com/p/how-to-performance-5c87d4da4665",
#   "https://medium.com/p/an-introduction-to-using-form-elements-in-react-3778042ff334",
#   "https://medium.com/p/cache-your-react-event-listeners-to-improve-performance-14f635a62e15",
#   "https://medium.com/p/reflections-on-clean-code-8c9b683277ca",
#   "https://medium.com/p/react-image-upload-with-kittens-cc96430eaece",
#   "https://medium.com/p/why-react16-is-a-blessing-to-react-developers-31433bfc210a",
#   "https://medium.com/p/subscribing-to-data-change-events-in-a-mysql-database-e60fe563a247",
#   "https://medium.com/p/career-changers-cracking-it-as-a-coder-e7d756b9ee95",
#   "https://medium.com/p/these-5-clean-code-tips-will-dramatically-improve-your-productivity-b20c152783b",
#   "https://medium.com/p/implement-tree-view-component-with-reactjs-and-styled-components-5eea3b1603cf",
#   "https://medium.com/p/react-webpack-and-babel-from-scratch-7aea5e768945",
#   "https://medium.com/p/a-pinterest-engineering-guide-to-technical-interviews-1c2471c2d139",
#   "https://medium.com/p/migrating-to-reacts-new-context-api-b15dc7a31ea0",
#   "https://medium.com/p/understanding-the-react-context-api-through-building-a-shared-snackbar-for-in-app-notifications-6c199446b80c",
#   "https://medium.com/p/react-tips-new-context-api-and-lifecycle-method-changes-b59ab0181dbb",
#   "https://medium.com/p/using-react-context-api-instead-of-redux-a617341c3b9f",
#   "https://medium.com/p/understanding-reacts-context-api-3ce1ac6cc1f2",
#   "https://medium.com/p/react-context-api-with-higher-order-component-279d5f93eda4",
#   "https://medium.com/p/before-using-react-context-289f4a4b14a6",
#   "https://medium.com/p/the-react-context-api-allows-you-to-pass-in-a-default-value-which-will-be-used-when-no-provider-51b6eff781c6",
#   "https://medium.com/p/react-context-api-a-replacement-for-redux-a7ddf73f2d79",
#   "https://medium.com/p/the-new-react-context-api-doesnt-replace-redux-at-all-bb498d775c69",
#   "https://medium.com/p/understanding-reacts-context-api-by-implementing-a-simple-snack-bar-ca8bef9a0e4b",
#   "https://medium.com/p/a-beginner-introduction-to-react-context-api-31e79ad40d8b",
#   "https://medium.com/p/react-context-api-as-an-alternative-to-redux-6b0c5d48c667",
#   "https://medium.com/p/simple-and-reusable-react-context-api-example-hoc-e1e50c0390ec",
#   "https://medium.com/p/using-react-context-api-to-share-state-between-component-89cad9a782cd",
#   "https://medium.com/p/how-to-build-a-react-state-manager-module-using-the-react-context-api-react-ctx-state-3611e9413a45",
#   "https://medium.com/p/optimizing-performance-while-using-new-react-context-api-3c85f1d44716",
#   "https://medium.com/p/understanding-and-using-reacts-context-api-6fe94bdac22e",
#   "https://medium.com/p/a-quick-intro-to-new-react-context-api-and-why-it-wont-replace-state-management-libraries-3b1def3d4e51",
#   "https://medium.com/p/the-new-react-context-api-is-not-a-redux-killer-fadc3c2198c8",
#   "https://medium.com/p/refactoring-redux-using-react-context-aa29fa16f4b7",
#   "https://medium.com/p/does-react-context-replace-redux-e50477b4de30",
#   "https://medium.com/p/implementing-the-new-react-context-api-f914387c6314",
#   "https://medium.com/p/a-short-review-of-when-you-should-be-using-the-react-context-api-cafcd49404ca",
#   "https://medium.com/p/a-look-at-the-react-context-api-bc07a5a567a6",
#   "https://medium.com/p/redux-is-dead-long-live-reacts-context-api-d0180f4278da",
#   "https://medium.com/p/using-reacts-context-api-to-provide-a-localization-toolbox-for-your-components-48915f04bb54",
#   "https://medium.com/p/react-context-api-2344dd784772",
#   "https://medium.com/p/using-the-react-context-api-to-set-and-read-state-ecc754f34d65",
#   "https://medium.com/p/combining-hocs-with-the-new-reacts-context-api-9d3617dccf0b",
#   "https://medium.com/p/everything-you-need-to-know-about-reacts-context-api-e5c8c32ef202",
#   "https://medium.com/p/how-react-context-api-works-detailed-4fc483d93fd0",
#   "https://medium.com/p/understanding-execution-context-and-execution-stack-in-javascript-1c9ea8642dd0",
#   "https://medium.com/p/react-16-3-whats-new-d69559fc743b",
#   "https://medium.com/p/heres-how-reacts-new-context-api-works-8a5ed3eec502",
#   "https://medium.com/p/why-you-should-consider-the-new-context-api-in-react-a-deep-dive-d588b66c57b5",
#   "https://medium.com/p/how-and-when-to-use-reacts-new-context-api-b584e41b2704",
#   "https://medium.com/p/react-context-api-managing-state-with-ease-e191dcadb73a",
#   "https://medium.com/p/a-walkthrough-guide-to-finding-an-engineering-job-at-slack-dc07dd7b0144",
#   "https://medium.com/p/component-folder-pattern-ee42df37ec68",
#   "https://medium.com/p/the-evolution-of-react-48409fac2efd",
#   "https://medium.com/p/learn-how-to-build-anti-fragile-systems-8bb685e52567",
#   "https://medium.com/p/a-beginners-guide-to-jest-testing-858d10198032",
#   "https://medium.com/p/how-we-avoided-if-else-and-wrote-extendable-code-with-strategy-pattern-256e34b90caf",
#   "https://medium.com/p/js-by-example-8-distinct-uses-of-javascript-array-slice-4e4e95a470e4",
#   "https://medium.com/p/designing-notifications-for-applications-3cad56fecf96",
#   "https://medium.com/p/building-semantic-data-catalogs-a72d0e1b821a",
#   "https://medium.com/p/making-a-submit-button-with-loader-wotw-85d7aaddd148",
#   "https://medium.com/p/styling-the-draft-js-editor-e14152a2472b",
#   "https://medium.com/p/draft-js-rich-text-editor-framework-for-react-from-facebook-f236d02576f0",
#   "https://medium.com/p/creating-a-rich-text-editor-part-1-barebones-editor-1a4cdf592d8b",
#   "https://medium.com/p/creating-a-rich-text-editor-part-2-text-styling-f6890e2750de",
#   "https://medium.com/p/creating-a-rich-text-editor-part-3-entities-and-decorators-a50c757ecc29",
#   "https://medium.com/p/draft-js-lists-depth-control-800fb3a6714c",
#   "https://medium.com/p/react-is-slow-react-is-fast-optimizing-react-apps-in-practice-394176a11fba",
#   "https://medium.com/p/oauth-in-react-redux-applications-5d69287211f3",
#   "https://medium.com/p/understanding-oauth2-and-building-a-basic-authorization-server-of-your-own-a-beginners-guide-cf7451a16f66",
#   "https://medium.com/p/how-to-build-your-first-shopify-app-bc4edef32974",
#   "https://medium.com/p/8-key-react-component-decisions-cc965db11594",
#   "https://medium.com/p/react-lifecycle-methods-how-and-when-to-use-them-2111a1b692b1",
#   "https://medium.com/p/8-tips-for-dealing-with-large-react-codebases-aed6235500a4",
#   "https://medium.com/p/10-react-mini-patterns-c1da92f068c5",
#   "https://medium.com/p/designing-simpler-react-components-13a0061afd16",
#   "https://medium.com/p/the-2018-web-developer-roadmap-826b1b806e8d",
#   "https://medium.com/p/using-advanced-design-patterns-to-create-flexible-and-reusable-react-components-part-1-dd495fa1823",
#   "https://medium.com/p/guide-to-react-compound-components-9c4b3eb482e9",
#   "https://medium.com/p/3-easy-steps-to-writing-compound-components-5d4647b7bb7",
#   "https://medium.com/p/the-organized-chaos-of-programming-language-design-1e0a95067afb",
#   "https://medium.com/p/how-to-do-object-oriented-programming-the-right-way-1339c1a25286",
#   "https://medium.com/p/follow-these-simple-rules-and-youll-become-a-git-and-github-master-e1045057468f",
#   "https://medium.com/p/getting-started-with-docker-ab43bc00425d",
#   "https://medium.com/p/error-handling-in-javascript-a6172ccdf9af",
#   "https://medium.com/p/problematic-react-lifecycle-methods-are-going-away-in-react-17-4216acc7d58b",
#   "https://medium.com/p/harry-potter-and-information-architecture-c3004f47fa81",
#   "https://medium.com/p/sinister-ux-how-to-recognize-and-avoid-dark-ux-patterns-95acdb15767f",
#   "https://medium.com/p/the-10-commandments-of-good-products-d1d0a97b30ee",
#   "https://medium.com/p/26-daily-habits-highly-successful-people-have-and-the-rest-of-us-probably-dont-e7ed73e3c16f",
#   "https://medium.com/p/run-for-better-code-c8d23338577c",
#   "https://medium.com/p/graphql-schema-design-building-evolvable-schemas-1501f3c59ed5",
#   "https://medium.com/p/really-bad-design-exercises-5f9648993980",
#   "https://medium.com/p/an-oauth-2-0-introduction-for-beginners-6e386b19f7a9",
#   "https://medium.com/p/very-simple-api-permissions-in-rails-d37e21f09ff8",
#   "https://medium.com/p/rails-api-jwt-auth-vuejs-spa-part-2-roles-601e4372a7e7",
#   "https://medium.com/p/how-do-i-use-react-context-3eeb879169a2",
#   "https://medium.com/p/what-is-casl-or-how-can-you-build-a-castle-around-your-application-4d2daa0b1ab4",
#   "https://medium.com/p/casl-and-cancan-permissions-sharing-between-ui-and-api-5f1fa8b4bec",
#   "https://medium.com/p/css-grid-the-swiss-army-knife-for-cutting-website-and-application-layouts-c1bd7a6b4e56",
#   "https://medium.com/p/things-i-honestly-dont-want-to-see-in-your-portfolio-3d3497666ca8",
#   "https://medium.com/p/algorithms-to-make-you-more-effective-8ae8749be970",
#   "https://medium.com/p/good-programmer-vs-average-programmer-4a398889fe68",
#   "https://medium.com/p/design-principles-that-help-you-shape-the-best-user-experience-260ad3a1bb83",
#   "https://medium.com/p/flexbox-the-animated-tutorial-8075cbe4c1b2",
#   "https://medium.com/p/whats-new-in-es6-or-es2015-480edf104489",
#   "https://medium.com/p/how-to-nail-a-whiteboard-design-challenge-ba909eee9d5f",
#   "https://medium.com/p/5-awesome-portfolio-websites-by-shopify-designers-2f425a657bdf",
#   "https://medium.com/p/a-developers-guide-to-web-design-for-non-designers-1f64ce28c38d",
#   "https://medium.com/p/i-hire-software-developers-your-resume-is-the-reason-youre-not-getting-interviews-dc7b2520a2f1",
#   "https://medium.com/p/progressive-web-apps-101-the-what-why-and-how-4aa5e9065ac2",
#   "https://medium.com/p/the-brain-fatigued-javascripters-guide-to-modern-frontend-tooling-in-2018-9818a04e9ec5",
#   "https://medium.com/p/javascript-currying-vs-partial-application-4db5b2442be8",
#   "https://medium.com/p/write-less-do-more-with-javascript-es6-5fd4a8e50ee2",
#   "https://medium.com/p/users-dont-want-filters-they-want-better-content-3146f650b8f6",
#   "https://medium.com/p/function-composition-currying-in-real-life-e74c86302205",
#   "https://medium.com/p/restful-api-design-step-by-step-guide-2f2c9f9fcdbf",
#   "https://medium.com/p/defending-ux-design-decisions-8-essential-techniques-770a85b589d6",
#   "https://medium.com/p/date-ing-javascript-6203650b752c",
#   "https://medium.com/p/stateful-monads-in-javascript-part-1-f772ac26195c",
#   "https://medium.com/p/creating-a-task-management-application-with-grunt-and-coffeescript-3266fe65c4d0",
#   "https://medium.com/p/the-front-end-performance-checklist-speeds-up-your-web-developments-b68e1c7a0276",
#   "https://medium.com/p/javascripts-reduce-method-explained-by-going-on-a-diet-71cdeb625147",
#   "https://medium.com/p/the-art-of-computer-programming-by-donald-knuth-82e275c8764f",
#   "https://medium.com/p/the-only-mac-apps-you-need-for-a-productive-2018-5e1d6de787b7",
#   "https://medium.com/p/become-a-developer-and-get-your-first-job-fast-7b8ac26d84c6",
#   "https://medium.com/p/comparing-the-brain-activity-of-jazz-and-classical-pianists-1d78687fcbc0",
#   "https://medium.com/p/a-simple-explanation-of-oop-46a156581214",
#   "https://medium.com/p/dark-pattern-design-its-downright-unethical-irresponsible-c2a3612a1640",
#   "https://medium.com/p/mastering-the-spotify-api-part1-c836b89eb68e",
#   "https://medium.com/p/5-steps-to-speed-up-your-image-heavy-website-65c874a86966",
#   "https://medium.com/p/how-javascript-works-under-the-hood-of-css-and-js-animations-how-to-optimize-their-performance-db0e79586216",
#   "https://medium.com/p/patterns-for-using-react-with-statechart-based-state-machines-33e6ab754605",
#   "https://medium.com/p/that-data-looks-so-fetching-on-you-understanding-the-js-fetch-api-880eae0c8d25",
#   "https://medium.com/p/the-cost-of-javascript-in-2018-7d8950fbb5d4",
#   "https://medium.com/p/5-tools-for-faster-vue-js-app-development-ad7eda1ee6a8",
#   "https://medium.com/p/what-is-a-user-persona-and-how-is-it-relevant-to-ux-aeb3e6f02077",
#   "https://medium.com/p/how-i-built-a-mood-changing-animation-using-css-masks-565b16ed051f",
#   "https://medium.com/p/selectors-react-redux-reselect-9ab984688dd4",
#   "https://medium.com/p/javascript-es6-you-dont-really-need-to-learn-generators-96aa2e9114fa",
#   "https://medium.com/p/making-work-simpler-more-pleasant-and-more-productive-99628c40f949",
#   "https://medium.com/p/negative-space-in-ui-design-tips-and-best-practices-98311cb2ad16",
#   "https://medium.com/p/product-design-expectations-vs-reality-2e5b24473dc5",
#   "https://medium.com/p/design-system-resources-b9119ddf9790",
#   "https://medium.com/p/how-to-create-design-principles-that-people-actually-use-11b534bf2425",
#   "https://medium.com/p/software-architecture-the-difference-between-architecture-and-design-7936abdd5830",
#   "https://medium.com/p/the-product-designers-toolbox-dec90aa8323b",
#   "https://medium.com/p/how-to-think-like-a-programmer-lessons-in-problem-solving-d1d8bf1de7d2",
#   "https://medium.com/p/advanced-techniques-and-ideas-for-better-coding-skills-d632e9f9675",
#   "https://medium.com/p/guys-rest-apis-are-not-databases-60db4e1120e4",
#   "https://medium.com/p/if-youve-ever-configured-webpack-parcel-will-blow-your-mind-b615468cee78",
#   "https://medium.com/p/building-fluid-interfaces-ios-swift-9732bb934bf5",
#   "https://medium.com/p/understanding-static-in-javascript-10782149993",
#   "https://medium.com/p/youtube-background-music-for-coding-99b592a74dc8",
#   "https://medium.com/p/meta-skills-of-a-software-engineer-bed411f6685e",
#   "https://medium.com/p/how-to-visually-design-state-in-javascript-3a6a1aadab2b",
#   "https://medium.com/p/the-top-data-structures-you-should-know-for-your-next-coding-interview-36af0831f5e3",
#   "https://medium.com/p/a-crash-course-on-serverless-apis-with-express-and-mongodb-77774f7730fe",
#   "https://medium.com/p/sex-beer-and-coding-inside-facebooks-wild-early-days-in-palo-alto-7b447c143d52",
#   "https://medium.com/p/how-to-get-users-hooked-on-your-interfaces-f8fd89b913b3",
#   "https://medium.com/p/a-curated-collection-of-over-150-apis-to-build-great-products-fdcfa0f361bc",
#   "https://medium.com/p/i-created-the-exact-same-app-in-react-and-vue-here-are-the-differences-e9a1ae8077fd",
#   "https://medium.com/p/im-a-software-engineer-why-do-i-put-my-travel-blogging-experience-on-my-resum%C3%A9-d159f6f7d738",
#   "https://medium.com/p/7-software-engineer-resume-best-practices-7598636bdf3f",
#   "https://medium.com/p/3-common-resume-mistakes-for-entry-level-software-engineers-4a214afec3ad",
#   "https://medium.com/p/modals-in-react-f6c3ff9f4701",
#   "https://medium.com/p/angular-6-is-out-what-should-developers-and-businesses-expect-223e2b334357",
#   "https://medium.com/p/how-javascript-works-deep-dive-into-websockets-and-http-2-with-sse-how-to-pick-the-right-path-584e6b8e3bf7",
#   "https://medium.com/p/what-are-websockets-7bf0e2e1af2",
#   "https://medium.com/p/im-polling-spotify-because-they-have-no-websockets-ws-scaling-battery-drain-3cb7d3f5f2ad",
#   "https://medium.com/p/a-comparison-between-websockets-server-sent-events-and-polling-7a27c98cb1e3",
#   "https://medium.com/p/why-you-shouldnt-use-long-polling-fallbacks-for-websockets-c1fff32a064a",
#   "https://medium.com/p/http-vs-websockets-a-performance-comparison-da2533f13a77",
#   "https://medium.com/p/web-api-design-35df8167460",
#   "https://medium.com/p/do-you-really-need-websockets-343aed40aa9b",
#   "https://medium.com/p/the-new-york-times-timely-app-concept-27efe88e5d4b",
#   "https://medium.com/p/gestalt-principles-in-ui-design-6b75a41e9965",
#   "https://medium.com/p/learning-python-from-zero-to-hero-120ea540b567",
#   "https://medium.com/p/lean-api-product-development-3f2787e2f941",
#   "https://medium.com/p/7-basic-design-principles-we-forget-about-8f5c15d4b527",
#   "https://medium.com/p/when-ux-defines-cx-c7e6989219e7",
#   "https://medium.com/p/motion-in-ux-design-9-points-to-get-started-e891974dc7ee",
#   "https://medium.com/p/server-rendering-code-splitting-and-lazy-loading-with-react-router-v4-bfe596a6af70",
#   "https://medium.com/p/next-js-react-server-side-rendering-done-right-f9700078a3b6",
#   "https://medium.com/p/is-your-ux-portfolio-user-friendly-58899643304e",
#   "https://medium.com/p/why-sql-beating-nosql-what-this-means-for-future-of-data-time-series-database-348b777b847a",
#   "https://medium.com/p/bus-ticket-ux-makeover-5159726d2925",
#   "https://medium.com/p/how-to-write-a-good-software-design-document-66fcf019569c",
#   "https://medium.com/p/stop-calling-these-dark-design-patterns-or-dark-ux-these-are-simply-asshole-designs-bb02df378ba",
#   "https://medium.com/p/the-2-types-of-software-engineering-interviews-and-how-to-prepare-for-them-2e7bd4daa0b",
#   "https://medium.com/p/web-architecture-101-a3224e126947",
#   "https://medium.com/p/react-app-performance-optimization-5e59454983e4",
#   "https://medium.com/p/how-to-build-a-react-project-from-scratch-using-webpack-4-and-babel-56d4a26afd32",
#   "https://medium.com/p/effective-use-of-typescript-with-react-3a1389b6072a",
#   "https://medium.com/p/serverless-websockets-with-aws-lambda-fanout-15384bd30354",
#   "https://medium.com/p/principles-to-code-by-3c516ad61fcc",
#   "https://medium.com/p/fast-and-modern-front-end-setup-with-webpack-react-redux-router-saga-and-postcss-1360e9715d17",
#   "https://medium.com/p/why-higher-order-components-make-sense-fe4145b4e305",
#   "https://medium.com/p/38-actions-and-insights-to-become-a-better-software-architect-f135e2de9a1b",
#   "https://medium.com/p/the-100-correct-way-to-structure-a-react-app-or-why-theres-no-such-thing-3ede534ef1ed",
#   "https://medium.com/p/the-complete-illustrated-flexbox-tutorial-d35c085dbf35",
#   "https://medium.com/p/how-to-add-push-notifications-to-a-web-app-with-firebase-528a702e13e1",
#   "https://medium.com/p/push-notifications-and-real-time-notifications-in-web-application-89daeafbfe53",
#   "https://medium.com/p/introduction-to-the-browser-push-and-notifications-api-44c512468d2b",
#   "https://medium.com/p/5-ways-to-make-most-of-the-push-notifications-196515441af",
#   "https://medium.com/p/website-push-notifications-implementation-explained-f19cd66c1017",
#   "https://medium.com/p/firebase-cloud-notifications-on-web-with-react-and-redux-58a8b3a2a439",
#   "https://medium.com/p/integrating-push-notifications-in-your-node-react-web-app-4e8d8190a52c",
#   "https://medium.com/p/implementing-push-notifications-with-create-react-app-bf35cd25d870",
#   "https://medium.com/p/using-firebase-to-provide-real-time-notifications-2f86b2f7d499",
#   "https://medium.com/p/7-basic-rules-for-button-design-63dcdf5676b4",
#   "https://medium.com/p/how-draft-js-represents-rich-text-data-eeabb5f25cf2",
#   "https://medium.com/p/draft-js-update-editor-content-636d96e2c1a5",
#   "https://medium.com/p/how-to-store-draft-js-content-75207f390b46",
#   "https://medium.com/p/implementing-todo-list-in-draftjs-6a939bb81e32",
#   "https://medium.com/p/draft-js-and-redux-the-perfect-couple-f5342503becd",
#   "https://medium.com/p/draft-js-overview-with-code-snippets-56f740022854",
#   "https://medium.com/p/draft-js-custom-block-rendering-c4221710323a",
#   "https://medium.com/p/draft-js-editor-with-hashtags-and-mentions-part-1-9dd54485a2d3",
#   "https://medium.com/p/best-practices-when-working-with-draft-js-81bd27e8aac3",
#   "https://medium.com/p/draft-js-building-search-and-replace-functionality-688fd84f64cb",
#   "https://medium.com/p/a-beginner-s-guide-to-draft-js-d1823f58d8cc",
#   "https://medium.com/p/timsort-the-fastest-sorting-algorithm-youve-never-heard-of-36b28417f399",
#   "https://medium.com/p/design-systems-at-github-c8e5378d2542",
#   "https://medium.com/p/data-structures-linked-list-implementation-in-js-3beb48ff49cd",
#   "https://medium.com/p/react-component-patterns-e7fb75be7bb0",
#   "https://medium.com/p/microinteractions-detailed-design-9113c88946d0",
#   "https://medium.com/p/3-practical-cheat-sheets-for-designing-attention-grabbing-uis-318e588bd864",
#   "https://medium.com/p/better-ux-through-microinteractions-680cbe22b110",
#   "https://medium.com/p/ux-digest-w9-2018-microinteractions-acb450e23276",
#   "https://medium.com/p/microinteractions-a-walkthrough-bb8de322ddf7",
#   "https://medium.com/p/micro-interactions-101-what-designers-need-to-know-13e7e297dd82",
#   "https://medium.com/p/the-thinking-behind-micro-interaction-b6e9f7010491",
#   "https://medium.com/p/micro-interactions-a-complete-beginners-guide-b446d90215ec",
#   "https://medium.com/p/boost-your-design-by-micro-interactions-9fdb628e42ec",
#   "https://medium.com/p/micro-interactions-why-when-and-how-to-use-them-to-boost-the-ux-17094b3baaa0",
#   "https://medium.com/p/5-mistakes-to-avoid-when-designing-micro-interactions-a6f638ee6a86",
#   "https://medium.com/p/u15-latest-and-best-loading-animations-to-make-user-enjoy-waiting-9c7861ed5d47",
#   "https://medium.com/p/adding-a-robust-form-validation-to-react-redux-apps-616ca240c124",
#   "https://medium.com/p/6-minute-beginners-guide-to-css-flexbox-527b3ff3480b",
#   "https://medium.com/p/5-common-practices-that-you-can-stop-doing-in-react-9e866df5d269",
#   "https://medium.com/p/its-time-to-remove-proptypes-and-just-use-flow-for-react-4a3de615aac5",
#   "https://medium.com/p/javascript-async-await-the-good-part-pitfalls-and-how-to-use-9b759ca21cda",
#   "https://medium.com/p/how-to-properly-structure-your-react-applications-5609ad3f2ee6",
#   "https://medium.com/p/using-redux-observable-to-handle-asynchronous-logic-in-redux-d49194742522",
#   "https://medium.com/p/how-to-use-react-createref-ea014ad09dba",
#   "https://medium.com/p/how-to-develop-an-eye-for-design-c5a4c64bb26c",
#   "https://medium.com/p/4-four-ways-to-style-react-components-ac6f323da822",
#   "https://medium.com/p/top-10-es6-features-by-example-80ac878794bb",
#   "https://medium.com/p/weekly-inspiration-for-designers-162-8433ff923bd",
#   "https://medium.com/p/rest-vs-graphql-a-critical-review-5f77392658e7",
#   "https://medium.com/p/how-to-build-a-range-slider-component-in-react-from-scratch-using-only-div-and-span-d53e1a62c4a3",
#   "https://medium.com/p/the-difference-between-function-and-block-scope-in-javascript-4296b2322abe",
#   "https://medium.com/p/javascript-es6-iterables-and-iterators-de18b54f4d4",
#   "https://medium.com/p/what-are-the-best-practices-when-testing-rails-apps-1fcf0d7e7bf9",
#   "https://medium.com/p/five-tips-for-working-with-redux-in-large-applications-89452af4fdcb",
#   "https://medium.com/p/ui-interactions-of-the-week-133-bf8578b14459",
#   "https://medium.com/p/learning-react-roadmap-from-scratch-to-advanced-bff7735531b6",
#   "https://medium.com/p/you-learned-the-basics-of-react-now-what-389e69be3c5a",
#   "https://medium.com/p/v4-create-react-redux-app-structure-with-build-configurations-whats-new-523bdec328c6",
#   "https://medium.com/p/react-redux-tips-and-best-practices-for-clean-reliable-maintainable-code-4daa068e1a4d",
#   "https://medium.com/p/learn-react-fundamentals-and-advanced-patterns-eac90341c9db",
#   "https://medium.com/p/updated-advanced-react-component-patterns-51c34b44b1df",
#   "https://medium.com/p/advanced-react-router-concepts-code-splitting-animated-transitions-scroll-restoration-recursive-17096c0cf9db",
#   "https://medium.com/p/top-resources-to-explore-react-fiber-9a2b19114520",
#   "https://medium.com/p/how-javascript-works-service-workers-their-life-cycle-and-use-cases-52b19ad98b58",
#   "https://medium.com/p/how-javascript-works-the-building-blocks-of-web-workers-5-cases-when-you-should-use-them-a547c0757f6a",
#   "https://medium.com/p/achieve-more-reactivity-with-web-workers-and-queues-dac461ec5f8e",
#   "https://medium.com/p/using-web-workers-react-and-webpack-d2773e3f362d",
#   "https://medium.com/p/introduction-to-service-workers-7fe055aad48d",
#   "https://medium.com/p/running-fetch-in-a-web-worker-700dc33ac854",
#   "https://medium.com/p/web-workers-to-the-rescue-4ecf4279953c",
#   "https://medium.com/p/how-to-use-web-workers-with-react-create-app-and-not-ejecting-in-the-attempt-3718d2a1166b",
#   "https://medium.com/p/creating-a-simple-chatroom-with-websockets-actioncable-759246c2d55d",
#   "https://medium.com/p/rails-react-webpacker-actioncable-283c6ac86ddb",
#   "https://medium.com/p/connect-an-autonomous-js-app-to-actioncable-for-realtime-goodness-5a76a05c7594",
#   "https://medium.com/p/set-up-a-chat-app-backend-with-rails-action-cable-d60f0a6e63c1",
#   "https://medium.com/p/bringing-beer-lovers-together-through-react-and-actioncable-d618a4a4a235",
#   "https://medium.com/p/actioncable-authentication-in-a-token-based-rails-api-f9cc4b8bf560",
#   "https://medium.com/p/how-to-use-rails-5-action-cable-to-build-a-chat-system-with-multiple-private-rooms-with-multiple-5bf82d98a5aa",
#   "https://medium.com/p/how-to-setup-real-time-data-flow-with-action-cable-rails-and-react-js-5da0f46a402c",
#   "https://medium.com/p/optimizing-react-app-performance-using-web-workers-79266afd4a7",
#   "https://medium.com/p/how-web-workers-can-help-with-consistent-asynchronous-tasks-in-javascript-cd6d728fa4ee",
#   "https://medium.com/p/what-are-web-sockets-what-about-rest-apis-b9c15fd72aac",
#   "https://medium.com/p/how-to-build-a-chat-application-using-react-redux-redux-saga-and-web-sockets-47423e4bc21a",
#   "https://medium.com/p/reactjs-ruby-on-rails-api-heroku-app-2645c93f0814",
#   "https://medium.com/p/react-devtools-c2d56a901f37",
#   "https://medium.com/p/build-a-desktop-chat-app-with-react-electron-and-chatkit-744d168e6f2f",
#   "https://medium.com/p/when-and-why-you-should-use-es6-arrow-functions-and-when-you-shouldnt-3d851d7f0b26",
#   "https://medium.com/p/ceiling-analysis-in-deep-learning-and-software-development-8bc41e59364a",
#   "https://medium.com/p/user-centered-growth-design-97a53d829807",
#   "https://medium.com/p/react-inline-functions-and-performance-bdff784f5578",
#   "https://medium.com/p/declarative-routing-with-react-router-v4-7419c198e93f",
#   "https://medium.com/p/why-you-should-use-simpler-redux-for-react-redux-development-375b9b0e3cff",
#   "https://medium.com/p/database-stakeholder-display-of-design-research-results-aca7f6150525",
#   "https://medium.com/p/the-importance-of-readable-code-165895e939c7",
#   "https://medium.com/p/tips-on-react-for-large-scale-projects-3f9ece85983d",
#   "https://medium.com/p/shape-your-redux-store-like-your-database-98faa4754fd5",
#   "https://medium.com/p/ux-design-tools-for-2018-for-mac-and-pc-320a7be230c9",
#   "https://medium.com/p/laying-the-foundation-rebuilding-articles-on-the-atlantic-90ae00263636",
#   "https://medium.com/p/improving-performance-at-the-atlantic-3284aee4b9ea",
#   "https://medium.com/p/do-more-with-less-using-render-props-de5bcdfbe74c",
#   "https://medium.com/p/graphql-front-end-queries-made-easy-68e9d9ded283",
#   "https://medium.com/p/10-javascript-concepts-you-need-to-know-for-interviews-136df65ecce",
#   "https://medium.com/p/stack-overflow-2018-developer-survey-faac8d3eb357",
#   "https://medium.com/p/create-a-beautiful-landing-page-animation-with-css-8f4501c20c8e",
#   "https://medium.com/p/the-hash-table-51516f49f347",
#   "https://medium.com/p/learn-these-javascript-fundamentals-and-become-a-better-developer-2a031a0dc9cf",
#   "https://medium.com/p/frontend-in-the-backend-a-pattern-for-cleaner-code-b497c92d0b49",
#   "https://medium.com/p/follow-these-steps-to-solve-any-dynamic-programming-interview-problem-cc98e508cd0e",
#   "https://medium.com/p/higher-order-components-the-ultimate-guide-b453a68bb851",
#   "https://medium.com/p/animated-transitions-with-react-router-a0ad00e633f1",
#   "https://medium.com/p/a-comprehensive-guide-to-react-js-in-2018-ba8bb6975597",
#   "https://medium.com/p/server-rendering-with-react-and-react-router-e0b7ba37653f",
#   "https://medium.com/p/redesigning-redux-b2baee8b8a38",
#   "https://medium.com/p/react-js-top-10-articles-for-the-past-month-v-apr-2018-e3cccab07012",
#   "https://medium.com/p/introducing-the-graphql-guide-11a5ae48628a",
#   "https://medium.com/p/complex-app-logic-with-redux-and-redux-saga-write-an-authentication-monitor-2f5672303d7d",
#   "https://medium.com/p/when-to-use-control-props-or-state-reducers-6cd83e42c5b",
#   "https://medium.com/p/testing-your-react-app-with-puppeteer-and-jest-c72b3dfcde59",
#   "https://medium.com/p/introducing-the-single-element-pattern-dfbd2c295c5d",
#   "https://medium.com/p/understanding-redux-the-worlds-easiest-guide-to-beginning-redux-c695f45546f6",
#   "https://medium.com/p/17-interactive-site-designs-youll-want-to-steal-30a5bd6d500c",
#   "https://medium.com/p/css-grid-vs-flexbox-building-simple-layouts-43e569a66f0a",
#   "https://medium.com/p/how-to-use-visual-cues-in-web-design-a23febee9039",
#   "https://medium.com/p/understanding-basic-concepts-of-css-flexbox-ffa657dc39c1",
#   "https://medium.com/p/learn-javascript-es-2017-string-padding-padstart-padend-88e90783e7de",
#   "https://medium.com/p/how-to-build-a-simple-blog-using-react-and-graphql-4a680b6e3206",
#   "https://medium.com/p/the-ui-and-ux-design-pocket-guide-volume-one-dfb3675ea828",
#   "https://medium.com/p/harnessing-the-power-of-react-in-design-prototyping-4a74e70db5f5",
#   "https://medium.com/p/atomic-design-with-react-e7aea8152957",
#   "https://medium.com/p/how-to-write-better-code-in-react-best-practices-b8ca87d462b0",
#   "https://medium.com/p/11-react-component-libraries-you-should-know-178eb1dd6aa4",
#   "https://medium.com/p/atomic-components-managing-dynamic-react-components-using-atomic-design-part-1-5f07451f261f",
#   "https://medium.com/p/evolving-patterns-in-react-116140e5fe8f",
#   "https://medium.com/p/moving-form-redux-thunk-to-redux-saga-5c19d0011ca0",
#   "https://medium.com/p/painless-end-to-end-testing-using-puppeteer-and-jest-11325e81fb6d",
#   "https://medium.com/p/jest-react-and-preact-1ae20847ba92",
#   "https://medium.com/p/unit-testing-redux-actions-reducers-and-epics-with-jest-484f8a59f1f2",
#   "https://medium.com/p/tools-of-the-trade-react-testing-with-enzyme-and-jest-c70ba40f69a9",
#   "https://medium.com/p/reasons-to-love-jest-the-developer-experience-b00ec93df7bb",
#   "https://medium.com/p/javascript-quality-control-with-jest-and-eslint-b888eeb4b0c4",
#   "https://medium.com/p/implementing-basic-component-tests-using-jest-and-enzyme-d1d8788d627a",
#   "https://medium.com/p/applying-microservices-design-patterns-to-scale-react-app-development-2c1f9df88452",
#   "https://medium.com/p/ultimate-react-component-patterns-with-typescript-2-8-82990c516935",
#   "https://medium.com/p/using-advanced-design-patterns-to-create-flexible-and-reusable-react-components-part-2-react-3c5662b997ab",
#   "https://medium.com/p/using-advanced-design-patterns-to-create-flexible-and-reusable-react-components-part-3-render-d7517dfe72bc",
#   "https://medium.com/p/how-to-use-redux-on-highly-scalable-javascript-applications-4e4b8cb5ef38",
#   "https://medium.com/p/simplify-complex-ui-by-implementing-the-atomic-design-in-react-with-bit-f4ad116ec8db",
#   "https://medium.com/p/growth-engineering-at-netflix-accelerating-innovation-90eb8e70ce59",
#   "https://medium.com/p/how-to-use-the-new-react-context-api-fce011e7d87",
#   "https://medium.com/p/useful-javascript-array-and-object-methods-6c7971d93230",
#   "https://medium.com/p/11-javascript-utility-libraries-you-should-know-in-2018-3646fb31ade",
#   "https://medium.com/p/javascript-function-declaration-vs-expression-f5873b8c7b38",
#   "https://medium.com/p/javascript-es-2017-learn-object-keys-object-values-and-object-entries-2626682f9667",
#   "https://medium.com/p/7-javascript-methods-that-will-boost-your-skills-in-less-than-8-minutes-4cc4c3dca03f",
#   "https://medium.com/p/some-of-javascripts-most-useful-features-can-be-tricky-let-me-explain-them-4003d7bbed32",
#   "https://medium.com/p/react-context-api-a-replacement-for-redux-6e20790492b3",
#   "https://medium.com/p/javascript-code-cleanup-how-you-can-refactor-to-use-classes-3948118e4468",
#   "https://medium.com/p/draft-js-editor-with-hashtags-and-mentions-part-2-4986c119eca2",
#   "https://medium.com/p/how-to-better-organize-your-react-applications-2fd3ea1920f1",
#   "https://medium.com/p/react-component-patterns-ab1f09be2c82",
#   "https://medium.com/p/how-to-build-a-react-js-chat-app-in-10-minutes-c9233794642b",
#   "https://medium.com/p/putting-a-draft-js-wysiwyg-editor-into-your-react-project-8f82493a742",
#   "https://medium.com/p/how-to-display-draft-js-content-as-html-154a0b2bac27",
#   "https://medium.com/p/seeing-through-redux-with-lenses-112ecb250f4",
#   "https://medium.com/p/yes-react-is-taking-over-front-end-development-the-question-is-why-40837af8ab76",
#   "https://medium.com/p/the-new-york-times-now-on-apollo-b9a78a5038c",
#   "https://medium.com/p/how-to-write-medium-stories-people-will-actually-read-92e58a27c8d8",
#   "https://medium.com/p/how-to-test-api-authentication-in-rails-2804fd31a1ea",
#   "https://medium.com/p/build-awesome-forms-in-react-using-redux-form-d1e4c96f5850",
#   "https://medium.com/p/10-tips-for-better-redux-architecture-69250425af44",
#   "https://medium.com/p/what-medium-readers-are-hungry-for-df96ef92b289",
#   "https://medium.com/p/how-to-grow-your-audience-on-medium-307f879a3468",
#   "https://medium.com/p/the-art-and-science-of-tags-f3d0706949b0",
#   "https://medium.com/p/expanding-the-medium-partner-program-3be09dd146e4",
#   "https://medium.com/p/the-medium-model-3ec28c6f603a",
#   "https://medium.com/p/a-guide-to-technical-interviews-at-medium-49850139aa03",
#   "https://medium.com/p/2-fast-2-furious-migrating-mediums-codebase-without-slowing-down-84b1e33d81f4",
#   "https://medium.com/p/engineering-interviews-what-we-screen-for-af2d84122417",
#   "https://medium.com/p/engineering-interviews-refining-our-process-52fbc9510e91",
#   "https://medium.com/p/engineering-growth-frequently-asked-questions-e860b07ca4ab",
#   "https://medium.com/p/engineering-growth-appeals-process-25a2161ed582",
#   "https://medium.com/p/engineering-growth-assessing-progress-743620e70763",
#   "https://medium.com/p/engineering-growth-tracks-b1fad620787e",
#   "https://medium.com/p/engineering-growth-introduction-8ba7b78c8d6c",
#   "https://medium.com/p/engineering-growth-framework-overview-4e02ab330524",
#   "https://medium.com/p/mapping-mediums-tags-1b9a78d77cf0",
#   "https://medium.com/p/when-to-use-component-or-purecomponent-a60cfad01a81",
#   "https://medium.com/p/a-basic-react-redux-introductory-tutorial-adcc681eeb5e",
#   "https://medium.com/p/react-native-and-redux-part-1-754c13a440ba",
#   "https://medium.com/p/getting-started-with-react-redux-1baae4dcb99b",
#   "https://medium.com/p/redux-vs-react-context-87a7053c12df",
#   "https://medium.com/p/github-glitch-and-the-future-of-social-coding-5e6faa45c8f2",
#   "https://medium.com/p/rendering-large-lists-with-react-virtualized-82741907a6b3",
#   "https://medium.com/p/fractal-a-react-app-structure-for-infinite-scale-4dab943092af",
#   "https://medium.com/p/mindset-lessons-from-a-year-with-react-1de862421981",
#   "https://medium.com/p/render-props-in-react-6081b6fa3593",
#   "https://medium.com/p/build-a-chat-app-with-sentiment-analysis-using-next-js-c43ebf3ea643",
#   "https://medium.com/p/7-rules-for-creating-gorgeous-ui-part-1-559d4e805cda",
#   "https://medium.com/p/5-tools-for-faster-development-in-react-676f134050f2",
#   "https://medium.com/p/functional-setstate-is-the-future-of-react-374f30401b6b",
#   "https://medium.com/p/working-with-paginated-api-in-redux-be871818e444",
#   "https://medium.com/p/these-four-clean-code-tips-will-dramatically-improve-your-engineering-teams-productivity-b5bd121dd150",
#   "https://medium.com/p/building-a-text-editor-for-a-digital-first-newsroom-f1cb8367fc21",
#   "https://medium.com/p/front-end-architecture-part-1-file-structure-74bc2806fc4",
#   "https://medium.com/p/advanced-react-component-patterns-56af2b74bc5f",
#   "https://medium.com/p/using-reactjs-hoc-pattern-be-aware-of-the-side-effects-f52beae77703",
#   "https://medium.com/p/web-scraping-in-javascript-with-nanopipe-bb0ac5bc5560",
#   "https://medium.com/p/creating-a-pattern-for-the-new-react-context-api-ce87653e50b3",
#   "https://medium.com/p/the-tech-interview-cheatsheet-8e28d94f5f04",
#   "https://medium.com/p/visually-testing-react-components-using-the-eyes-storybook-sdk-33384a51f05e",
#   "https://medium.com/p/implement-linear-and-binary-search-algorithms-with-javascript-2149997588f0",
#   "https://medium.com/p/cracking-the-front-end-developer-interview-part-1-be3619b60cc4",
#   "https://medium.com/p/top-10-web-design-trends-to-follow-in-2018-79623d6ff3d2",
#   "https://medium.com/p/using-a-datepicker-in-react-js-b67e970195fd",
#   "https://medium.com/p/what-can-react-context-api-do-for-you-multi-language-text-modals-and-theme-switchers-9cfbc8e5ee5e",
#   "https://medium.com/p/learning-react-js-by-building-a-minesweeper-game-ced9d41560ed",
#   "https://medium.com/p/javascript-questions-to-ask-in-technical-interviews-fullstack-frontend-backend-84fec4db4c44",
#   "https://medium.com/p/basic-ecmascript-6-interview-questions-and-answers-e6e9f9b3ff2d",
#   "https://medium.com/p/understanding-react-react-16-3-component-life-cycle-23129bc7a705",
#   "https://medium.com/p/how-to-create-a-react-component-and-publish-it-in-npm-668ad7d363ce",
#   "https://medium.com/p/unit-testing-redux-connected-components-692fa3c4441c",
#   "https://medium.com/p/css-grid-responsive-layouts-and-components-eee1badd5a2f",
#   "https://medium.com/p/handling-race-conditions-with-redux-thunk-c348a7a5a839",
#   "https://medium.com/p/the-react-state-museum-a278c726315",
#   "https://medium.com/p/react-patterns-you-should-know-da86568372fa",
#   "https://medium.com/p/ivy-league-free-online-courses-a0d7ae675869"
# ]
# #
# # def create_url_array
# #   [page_1, page_2, page_3, page_4, page_5, page_6].map do |page|
# #     all_links.concat(Nokogiri::HTML(page).css("a.h-cite").map { |link| link['href'] })
# #   end
# # end
#
# def seed_db
#   @all_links.each do |link|
#     doc = Nokogiri::HTML(open(link))
#     a = Article.find_or_create_by(
#       title: doc.css("h1").inner_text,
#       content: doc.css("div.sectionLayout--insetColumn").inner_html
#     )
#     if doc.search('time').find{ |time| time.attributes } && doc.search('time').find{ |time| time.attributes.include?('datetime') }.attributes["datetime"].value
#       a.update(date: doc.search('time').find{ |time| time.attributes.include?('datetime') }.attributes["datetime"].value)
#     end
#
#     tags = doc.css('ul.tags li').map { |tag| tag.inner_text }
#     tags.each do |tag|
#       t = Tag.find_or_create_by(name: tag)
#       a.tags << t
#     end
#   end
# end
#
# def run
#   seed_db
# end
#
# run

class Scraper

  def all_links
    @all_links = ["https://medium.com/p/async-generators-as-an-alternative-to-state-management-f9871390ffca",
      "https://medium.com/p/using-modern-regexes-in-javascript-30322af557c5",
      "https://medium.com/p/es6-set-map-weak-a2aeb7e2d384",
      "https://medium.com/p/how-to-store-your-state-data-f17ceca37aa",
      "https://medium.com/p/es2015-built-ins-part-1-symbols-sets-and-maps-608f126dd906",
      "https://medium.com/p/reduce-filter-and-map-without-reduce-filter-and-map-787c21671c95",
      "https://medium.com/p/array-vs-set-vs-map-vs-object-real-time-use-cases-in-javascript-es6-47ee3295329b",
      "https://medium.com/p/performance-creating-map-object-create-null-d9265331f0d4",
      "https://medium.com/p/writing-javascript-with-map-reduce-980602ff2f2f",
      "https://medium.com/p/es2018-finally-method-in-native-promise-bb865834abba",
      "https://medium.com/p/learn-understand-javascripts-map-function-ffc059264783",
      "https://medium.com/p/es9-javascripts-state-of-art-in-2018-9a350643f29c",
      "https://medium.com/p/javascript-whats-new-in-ecmascript-2018-es2018-17ede97f36d5",
      "https://medium.com/p/es6-lets-divide-our-phones-into-classes-4574bd0454bf",
      "https://medium.com/p/es6-cool-stuffs-a-new-js-string-with-template-literals-c23a8af11b2",
      "https://medium.com/p/es6-cool-stuffs-destructuring-me-plz-b8f1335d241a",
      "https://medium.com/p/es6-cool-stuffs-var-let-and-const-in-depth-24512e593268",
      "https://medium.com/p/es6-magical-stuffs-spread-syntax-in-depth-afdd0118ebd0",
      "https://medium.com/p/es6-set-vs-array-what-and-when-efc055655e1a",
      "https://medium.com/p/javascript-learn-to-chain-map-filter-and-reduce-acd2d0562cd4",
      "https://medium.com/p/es6-map-vs-object-what-and-when-b80621932373",
      "https://medium.com/p/async-javascript-a-pocket-reference-2bb16ac40d21",
      "https://medium.com/p/coding-dynamic-behavior-with-the-strategy-pattern-c0bebaee6671",
      "https://medium.com/p/principles-of-component-api-prop-design-bb20cd58da54",
      "https://medium.com/p/rethinking-unit-test-assertions-55f59358253f",
      "https://medium.com/p/lets-clear-up-the-confusion-around-the-slice-splice-split-methods-in-javascript-8ba3266c29ae",
      "https://medium.com/p/the-3-steps-in-an-empirical-approach-for-analyzing-the-run-time-of-algorithms-f48d90e18908",
      "https://medium.com/p/what-i-learned-from-doing-1000-code-reviews-fe28d4d11c71",
      "https://medium.com/p/50-data-structure-and-algorithms-interview-questions-for-programmers-b4b1ac61f5b0",
      "https://medium.com/p/pocket-ceo-nate-weiner-explains-how-to-create-a-top-productivity-app-58f9b6cf76d9",
      "https://medium.com/p/how-to-impress-interviewers-by-using-recursion-in-javascript-with-es6-features-a14c763110d7",
      "https://medium.com/p/javascript-essentials-objects-56373a1a6bfb",
      "https://medium.com/p/javascript-arrow-functions-how-why-when-and-when-not-to-use-them-fb8c2de9dbdc",
      "https://medium.com/p/a-practical-es6-guide-on-how-to-perform-http-requests-using-the-fetch-api-594c3d91a547",
      "https://medium.com/p/10-technical-interview-tips-67bf962efaa0",
      "https://medium.com/p/coding-interviews-for-dummies-5e048933b82b",
      "https://medium.com/p/cracking-the-frontend-coding-interview-ec7d5b1e6755",
      "https://medium.com/p/testing-react-components-with-jest-and-enzyme-324a8684aad4",
      "https://medium.com/p/learning-to-write-react-tests-on-example-of-react-tic-tac-toe-app-acf7ae2b94b8",
      "https://medium.com/p/you-might-not-need-redux-be46360cf367",
      "https://medium.com/p/redux-thunk-vs-redux-saga-93fe82878b2d",
      "https://medium.com/p/how-to-not-suck-at-design-a-5-minute-guide-for-the-non-designer-291efac43037",
      "https://medium.com/p/the-common-genius-of-lincoln-and-einstein-84595b688cbc",
      "https://medium.com/p/react-redux-connect-when-and-how-to-use-it-f2a1edab2013",
      "https://medium.com/p/javascript-essentials-types-data-structures-3ac039f9877b",
      "https://medium.com/p/how-to-write-a-web-developer-r%C3%A9sum%C3%A9-that-will-help-you-get-an-interview-ee4fe95d9608",
      "https://medium.com/p/rails-5-api-jwt-setup-in-minutes-using-devise-71670fd4ed03",
      "https://medium.com/p/how-to-write-epic-unit-tests-with-typescript-jest-redux-and-rxjs-6-in-a-react-based-application-357497b2956a",
      "https://medium.com/p/how-to-absolutely-ace-developer-presentations-ef12548729ae",
      "https://medium.com/p/evolution-and-agile-b9f8f9f95924",
      "https://medium.com/p/a-short-guide-to-static-and-dynamic-libraries-a52acf6f7904",
      "https://medium.com/p/the-trick-to-thinking-clearer-and-better-4a61c54114fa",
      "https://medium.com/p/how-to-master-any-skill-92287046f55b",
      "https://medium.com/p/building-your-own-design-pattern-5f30b7d16122",
      "https://medium.com/p/dockerizing-spas-9f72b7867e41",
      "https://medium.com/p/5-easy-ways-to-make-your-ui-more-accessible-34a10522ae99",
      "https://medium.com/p/ux-vs-ui-vs-ia-vs-ixd-4-confusing-digital-design-terms-explained-222f3bcc3255",
      "https://medium.com/p/oh-mamma-im-in-love-with-gradient-c81943e3c92b",
      "https://medium.com/p/increasing-the-adoption-of-ux-and-the-products-you-design-part-1-8871cf8368d6",
      "https://medium.com/p/how-we-hire-front-end-engineers-at-the-new-york-times-e1294ea8e3f8",
      "https://medium.com/p/web-application-security-understanding-the-browser-5305ed2f1dac",
      "https://medium.com/p/mastering-react-functional-components-with-recompose-d4dd6ac98834",
      "https://medium.com/p/focus-and-deep-work-your-secret-weapons-to-becoming-a-10x-developer-8e203a6ad291",
      "https://medium.com/p/react-js-compound-components-a6e54b5c9992",
      "https://medium.com/p/implementing-the-async-await-syntax-for-promise-request-javascript-c4a193827bd2",
      "https://medium.com/p/how-to-performance-5c87d4da4665",
      "https://medium.com/p/an-introduction-to-using-form-elements-in-react-3778042ff334",
      "https://medium.com/p/cache-your-react-event-listeners-to-improve-performance-14f635a62e15",
      "https://medium.com/p/reflections-on-clean-code-8c9b683277ca",
      "https://medium.com/p/react-image-upload-with-kittens-cc96430eaece",
      "https://medium.com/p/why-react16-is-a-blessing-to-react-developers-31433bfc210a",
      "https://medium.com/p/subscribing-to-data-change-events-in-a-mysql-database-e60fe563a247",
      "https://medium.com/p/career-changers-cracking-it-as-a-coder-e7d756b9ee95",
      "https://medium.com/p/these-5-clean-code-tips-will-dramatically-improve-your-productivity-b20c152783b",
      "https://medium.com/p/implement-tree-view-component-with-reactjs-and-styled-components-5eea3b1603cf",
      "https://medium.com/p/react-webpack-and-babel-from-scratch-7aea5e768945",
      "https://medium.com/p/a-pinterest-engineering-guide-to-technical-interviews-1c2471c2d139",
      "https://medium.com/p/migrating-to-reacts-new-context-api-b15dc7a31ea0",
      "https://medium.com/p/understanding-the-react-context-api-through-building-a-shared-snackbar-for-in-app-notifications-6c199446b80c",
      "https://medium.com/p/react-tips-new-context-api-and-lifecycle-method-changes-b59ab0181dbb",
      "https://medium.com/p/using-react-context-api-instead-of-redux-a617341c3b9f",
      "https://medium.com/p/understanding-reacts-context-api-3ce1ac6cc1f2",
      "https://medium.com/p/react-context-api-with-higher-order-component-279d5f93eda4",
      "https://medium.com/p/before-using-react-context-289f4a4b14a6",
      "https://medium.com/p/the-react-context-api-allows-you-to-pass-in-a-default-value-which-will-be-used-when-no-provider-51b6eff781c6",
      "https://medium.com/p/react-context-api-a-replacement-for-redux-a7ddf73f2d79",
      "https://medium.com/p/the-new-react-context-api-doesnt-replace-redux-at-all-bb498d775c69",
      "https://medium.com/p/understanding-reacts-context-api-by-implementing-a-simple-snack-bar-ca8bef9a0e4b",
      "https://medium.com/p/a-beginner-introduction-to-react-context-api-31e79ad40d8b",
      "https://medium.com/p/react-context-api-as-an-alternative-to-redux-6b0c5d48c667",
      "https://medium.com/p/simple-and-reusable-react-context-api-example-hoc-e1e50c0390ec",
      "https://medium.com/p/using-react-context-api-to-share-state-between-component-89cad9a782cd",
      "https://medium.com/p/how-to-build-a-react-state-manager-module-using-the-react-context-api-react-ctx-state-3611e9413a45",
      "https://medium.com/p/optimizing-performance-while-using-new-react-context-api-3c85f1d44716",
      "https://medium.com/p/understanding-and-using-reacts-context-api-6fe94bdac22e",
      "https://medium.com/p/a-quick-intro-to-new-react-context-api-and-why-it-wont-replace-state-management-libraries-3b1def3d4e51",
      "https://medium.com/p/the-new-react-context-api-is-not-a-redux-killer-fadc3c2198c8",
      "https://medium.com/p/refactoring-redux-using-react-context-aa29fa16f4b7",
      "https://medium.com/p/does-react-context-replace-redux-e50477b4de30",
      "https://medium.com/p/implementing-the-new-react-context-api-f914387c6314",
      "https://medium.com/p/a-short-review-of-when-you-should-be-using-the-react-context-api-cafcd49404ca",
      "https://medium.com/p/a-look-at-the-react-context-api-bc07a5a567a6",
      "https://medium.com/p/redux-is-dead-long-live-reacts-context-api-d0180f4278da",
      "https://medium.com/p/using-reacts-context-api-to-provide-a-localization-toolbox-for-your-components-48915f04bb54",
      "https://medium.com/p/react-context-api-2344dd784772",
      "https://medium.com/p/using-the-react-context-api-to-set-and-read-state-ecc754f34d65",
      "https://medium.com/p/combining-hocs-with-the-new-reacts-context-api-9d3617dccf0b",
      "https://medium.com/p/everything-you-need-to-know-about-reacts-context-api-e5c8c32ef202",
      "https://medium.com/p/how-react-context-api-works-detailed-4fc483d93fd0",
      "https://medium.com/p/understanding-execution-context-and-execution-stack-in-javascript-1c9ea8642dd0",
      "https://medium.com/p/react-16-3-whats-new-d69559fc743b",
      "https://medium.com/p/heres-how-reacts-new-context-api-works-8a5ed3eec502",
      "https://medium.com/p/why-you-should-consider-the-new-context-api-in-react-a-deep-dive-d588b66c57b5",
      "https://medium.com/p/how-and-when-to-use-reacts-new-context-api-b584e41b2704",
      "https://medium.com/p/react-context-api-managing-state-with-ease-e191dcadb73a",
      "https://medium.com/p/a-walkthrough-guide-to-finding-an-engineering-job-at-slack-dc07dd7b0144",
      "https://medium.com/p/component-folder-pattern-ee42df37ec68",
      "https://medium.com/p/the-evolution-of-react-48409fac2efd",
      "https://medium.com/p/learn-how-to-build-anti-fragile-systems-8bb685e52567",
      "https://medium.com/p/a-beginners-guide-to-jest-testing-858d10198032",
      "https://medium.com/p/how-we-avoided-if-else-and-wrote-extendable-code-with-strategy-pattern-256e34b90caf",
      "https://medium.com/p/js-by-example-8-distinct-uses-of-javascript-array-slice-4e4e95a470e4",
      "https://medium.com/p/designing-notifications-for-applications-3cad56fecf96",
      "https://medium.com/p/building-semantic-data-catalogs-a72d0e1b821a",
      "https://medium.com/p/making-a-submit-button-with-loader-wotw-85d7aaddd148",
      "https://medium.com/p/styling-the-draft-js-editor-e14152a2472b",
      "https://medium.com/p/draft-js-rich-text-editor-framework-for-react-from-facebook-f236d02576f0",
      "https://medium.com/p/creating-a-rich-text-editor-part-1-barebones-editor-1a4cdf592d8b",
      "https://medium.com/p/creating-a-rich-text-editor-part-2-text-styling-f6890e2750de",
      "https://medium.com/p/creating-a-rich-text-editor-part-3-entities-and-decorators-a50c757ecc29",
      "https://medium.com/p/draft-js-lists-depth-control-800fb3a6714c",
      "https://medium.com/p/react-is-slow-react-is-fast-optimizing-react-apps-in-practice-394176a11fba",
      "https://medium.com/p/oauth-in-react-redux-applications-5d69287211f3",
      "https://medium.com/p/understanding-oauth2-and-building-a-basic-authorization-server-of-your-own-a-beginners-guide-cf7451a16f66",
      "https://medium.com/p/how-to-build-your-first-shopify-app-bc4edef32974",
      "https://medium.com/p/8-key-react-component-decisions-cc965db11594",
      "https://medium.com/p/react-lifecycle-methods-how-and-when-to-use-them-2111a1b692b1",
      "https://medium.com/p/8-tips-for-dealing-with-large-react-codebases-aed6235500a4",
      "https://medium.com/p/10-react-mini-patterns-c1da92f068c5",
      "https://medium.com/p/designing-simpler-react-components-13a0061afd16",
      "https://medium.com/p/the-2018-web-developer-roadmap-826b1b806e8d",
      "https://medium.com/p/using-advanced-design-patterns-to-create-flexible-and-reusable-react-components-part-1-dd495fa1823",
      "https://medium.com/p/guide-to-react-compound-components-9c4b3eb482e9",
      "https://medium.com/p/3-easy-steps-to-writing-compound-components-5d4647b7bb7",
      "https://medium.com/p/the-organized-chaos-of-programming-language-design-1e0a95067afb",
      "https://medium.com/p/how-to-do-object-oriented-programming-the-right-way-1339c1a25286",
      "https://medium.com/p/follow-these-simple-rules-and-youll-become-a-git-and-github-master-e1045057468f",
      "https://medium.com/p/getting-started-with-docker-ab43bc00425d",
      "https://medium.com/p/error-handling-in-javascript-a6172ccdf9af",
      "https://medium.com/p/problematic-react-lifecycle-methods-are-going-away-in-react-17-4216acc7d58b",
      "https://medium.com/p/harry-potter-and-information-architecture-c3004f47fa81",
      "https://medium.com/p/sinister-ux-how-to-recognize-and-avoid-dark-ux-patterns-95acdb15767f",
      "https://medium.com/p/the-10-commandments-of-good-products-d1d0a97b30ee",
      "https://medium.com/p/26-daily-habits-highly-successful-people-have-and-the-rest-of-us-probably-dont-e7ed73e3c16f",
      "https://medium.com/p/run-for-better-code-c8d23338577c",
      "https://medium.com/p/graphql-schema-design-building-evolvable-schemas-1501f3c59ed5",
      "https://medium.com/p/really-bad-design-exercises-5f9648993980",
      "https://medium.com/p/an-oauth-2-0-introduction-for-beginners-6e386b19f7a9",
      "https://medium.com/p/very-simple-api-permissions-in-rails-d37e21f09ff8",
      "https://medium.com/p/rails-api-jwt-auth-vuejs-spa-part-2-roles-601e4372a7e7",
      "https://medium.com/p/how-do-i-use-react-context-3eeb879169a2",
      "https://medium.com/p/what-is-casl-or-how-can-you-build-a-castle-around-your-application-4d2daa0b1ab4",
      "https://medium.com/p/casl-and-cancan-permissions-sharing-between-ui-and-api-5f1fa8b4bec",
      "https://medium.com/p/css-grid-the-swiss-army-knife-for-cutting-website-and-application-layouts-c1bd7a6b4e56",
      "https://medium.com/p/things-i-honestly-dont-want-to-see-in-your-portfolio-3d3497666ca8",
      "https://medium.com/p/algorithms-to-make-you-more-effective-8ae8749be970",
      "https://medium.com/p/good-programmer-vs-average-programmer-4a398889fe68",
      "https://medium.com/p/design-principles-that-help-you-shape-the-best-user-experience-260ad3a1bb83",
      "https://medium.com/p/flexbox-the-animated-tutorial-8075cbe4c1b2",
      "https://medium.com/p/whats-new-in-es6-or-es2015-480edf104489",
      "https://medium.com/p/how-to-nail-a-whiteboard-design-challenge-ba909eee9d5f",
      "https://medium.com/p/5-awesome-portfolio-websites-by-shopify-designers-2f425a657bdf",
      "https://medium.com/p/a-developers-guide-to-web-design-for-non-designers-1f64ce28c38d",
      "https://medium.com/p/i-hire-software-developers-your-resume-is-the-reason-youre-not-getting-interviews-dc7b2520a2f1",
      "https://medium.com/p/progressive-web-apps-101-the-what-why-and-how-4aa5e9065ac2",
      "https://medium.com/p/the-brain-fatigued-javascripters-guide-to-modern-frontend-tooling-in-2018-9818a04e9ec5",
      "https://medium.com/p/javascript-currying-vs-partial-application-4db5b2442be8",
      "https://medium.com/p/write-less-do-more-with-javascript-es6-5fd4a8e50ee2",
      "https://medium.com/p/users-dont-want-filters-they-want-better-content-3146f650b8f6",
      "https://medium.com/p/function-composition-currying-in-real-life-e74c86302205",
      "https://medium.com/p/restful-api-design-step-by-step-guide-2f2c9f9fcdbf",
      "https://medium.com/p/defending-ux-design-decisions-8-essential-techniques-770a85b589d6",
      "https://medium.com/p/date-ing-javascript-6203650b752c",
      "https://medium.com/p/stateful-monads-in-javascript-part-1-f772ac26195c",
      "https://medium.com/p/creating-a-task-management-application-with-grunt-and-coffeescript-3266fe65c4d0",
      "https://medium.com/p/the-front-end-performance-checklist-speeds-up-your-web-developments-b68e1c7a0276",
      "https://medium.com/p/javascripts-reduce-method-explained-by-going-on-a-diet-71cdeb625147",
      "https://medium.com/p/the-art-of-computer-programming-by-donald-knuth-82e275c8764f",
      "https://medium.com/p/the-only-mac-apps-you-need-for-a-productive-2018-5e1d6de787b7",
      "https://medium.com/p/become-a-developer-and-get-your-first-job-fast-7b8ac26d84c6",
      "https://medium.com/p/comparing-the-brain-activity-of-jazz-and-classical-pianists-1d78687fcbc0",
      "https://medium.com/p/a-simple-explanation-of-oop-46a156581214",
      "https://medium.com/p/dark-pattern-design-its-downright-unethical-irresponsible-c2a3612a1640",
      "https://medium.com/p/mastering-the-spotify-api-part1-c836b89eb68e",
      "https://medium.com/p/5-steps-to-speed-up-your-image-heavy-website-65c874a86966",
      "https://medium.com/p/how-javascript-works-under-the-hood-of-css-and-js-animations-how-to-optimize-their-performance-db0e79586216",
      "https://medium.com/p/patterns-for-using-react-with-statechart-based-state-machines-33e6ab754605",
      "https://medium.com/p/that-data-looks-so-fetching-on-you-understanding-the-js-fetch-api-880eae0c8d25",
      "https://medium.com/p/the-cost-of-javascript-in-2018-7d8950fbb5d4",
      "https://medium.com/p/5-tools-for-faster-vue-js-app-development-ad7eda1ee6a8",
      "https://medium.com/p/what-is-a-user-persona-and-how-is-it-relevant-to-ux-aeb3e6f02077",
      "https://medium.com/p/how-i-built-a-mood-changing-animation-using-css-masks-565b16ed051f",
      "https://medium.com/p/selectors-react-redux-reselect-9ab984688dd4",
      "https://medium.com/p/javascript-es6-you-dont-really-need-to-learn-generators-96aa2e9114fa",
      "https://medium.com/p/making-work-simpler-more-pleasant-and-more-productive-99628c40f949",
      "https://medium.com/p/negative-space-in-ui-design-tips-and-best-practices-98311cb2ad16",
      "https://medium.com/p/product-design-expectations-vs-reality-2e5b24473dc5",
      "https://medium.com/p/design-system-resources-b9119ddf9790",
      "https://medium.com/p/how-to-create-design-principles-that-people-actually-use-11b534bf2425",
      "https://medium.com/p/software-architecture-the-difference-between-architecture-and-design-7936abdd5830",
      "https://medium.com/p/the-product-designers-toolbox-dec90aa8323b",
      "https://medium.com/p/how-to-think-like-a-programmer-lessons-in-problem-solving-d1d8bf1de7d2",
      "https://medium.com/p/advanced-techniques-and-ideas-for-better-coding-skills-d632e9f9675",
      "https://medium.com/p/guys-rest-apis-are-not-databases-60db4e1120e4",
      "https://medium.com/p/if-youve-ever-configured-webpack-parcel-will-blow-your-mind-b615468cee78",
      "https://medium.com/p/building-fluid-interfaces-ios-swift-9732bb934bf5",
      "https://medium.com/p/understanding-static-in-javascript-10782149993",
      "https://medium.com/p/youtube-background-music-for-coding-99b592a74dc8",
      "https://medium.com/p/meta-skills-of-a-software-engineer-bed411f6685e",
      "https://medium.com/p/how-to-visually-design-state-in-javascript-3a6a1aadab2b",
      "https://medium.com/p/the-top-data-structures-you-should-know-for-your-next-coding-interview-36af0831f5e3",
      "https://medium.com/p/a-crash-course-on-serverless-apis-with-express-and-mongodb-77774f7730fe",
      "https://medium.com/p/sex-beer-and-coding-inside-facebooks-wild-early-days-in-palo-alto-7b447c143d52",
      "https://medium.com/p/how-to-get-users-hooked-on-your-interfaces-f8fd89b913b3",
      "https://medium.com/p/a-curated-collection-of-over-150-apis-to-build-great-products-fdcfa0f361bc",
      "https://medium.com/p/i-created-the-exact-same-app-in-react-and-vue-here-are-the-differences-e9a1ae8077fd",
      "https://medium.com/p/im-a-software-engineer-why-do-i-put-my-travel-blogging-experience-on-my-resum%C3%A9-d159f6f7d738",
      "https://medium.com/p/7-software-engineer-resume-best-practices-7598636bdf3f",
      "https://medium.com/p/3-common-resume-mistakes-for-entry-level-software-engineers-4a214afec3ad",
      "https://medium.com/p/modals-in-react-f6c3ff9f4701",
      "https://medium.com/p/angular-6-is-out-what-should-developers-and-businesses-expect-223e2b334357",
      "https://medium.com/p/how-javascript-works-deep-dive-into-websockets-and-http-2-with-sse-how-to-pick-the-right-path-584e6b8e3bf7",
      "https://medium.com/p/what-are-websockets-7bf0e2e1af2",
      "https://medium.com/p/im-polling-spotify-because-they-have-no-websockets-ws-scaling-battery-drain-3cb7d3f5f2ad",
      "https://medium.com/p/a-comparison-between-websockets-server-sent-events-and-polling-7a27c98cb1e3",
      "https://medium.com/p/why-you-shouldnt-use-long-polling-fallbacks-for-websockets-c1fff32a064a",
      "https://medium.com/p/http-vs-websockets-a-performance-comparison-da2533f13a77",
      "https://medium.com/p/web-api-design-35df8167460",
      "https://medium.com/p/do-you-really-need-websockets-343aed40aa9b",
      "https://medium.com/p/the-new-york-times-timely-app-concept-27efe88e5d4b",
      "https://medium.com/p/gestalt-principles-in-ui-design-6b75a41e9965",
      "https://medium.com/p/learning-python-from-zero-to-hero-120ea540b567",
      "https://medium.com/p/lean-api-product-development-3f2787e2f941",
      "https://medium.com/p/7-basic-design-principles-we-forget-about-8f5c15d4b527",
      "https://medium.com/p/when-ux-defines-cx-c7e6989219e7",
      "https://medium.com/p/motion-in-ux-design-9-points-to-get-started-e891974dc7ee",
      "https://medium.com/p/server-rendering-code-splitting-and-lazy-loading-with-react-router-v4-bfe596a6af70",
      "https://medium.com/p/next-js-react-server-side-rendering-done-right-f9700078a3b6",
      "https://medium.com/p/is-your-ux-portfolio-user-friendly-58899643304e",
      "https://medium.com/p/why-sql-beating-nosql-what-this-means-for-future-of-data-time-series-database-348b777b847a",
      "https://medium.com/p/bus-ticket-ux-makeover-5159726d2925",
      "https://medium.com/p/how-to-write-a-good-software-design-document-66fcf019569c",
      "https://medium.com/p/stop-calling-these-dark-design-patterns-or-dark-ux-these-are-simply-asshole-designs-bb02df378ba",
      "https://medium.com/p/the-2-types-of-software-engineering-interviews-and-how-to-prepare-for-them-2e7bd4daa0b",
      "https://medium.com/p/web-architecture-101-a3224e126947",
      "https://medium.com/p/react-app-performance-optimization-5e59454983e4",
      "https://medium.com/p/how-to-build-a-react-project-from-scratch-using-webpack-4-and-babel-56d4a26afd32",
      "https://medium.com/p/effective-use-of-typescript-with-react-3a1389b6072a",
      "https://medium.com/p/serverless-websockets-with-aws-lambda-fanout-15384bd30354",
      "https://medium.com/p/principles-to-code-by-3c516ad61fcc",
      "https://medium.com/p/fast-and-modern-front-end-setup-with-webpack-react-redux-router-saga-and-postcss-1360e9715d17",
      "https://medium.com/p/why-higher-order-components-make-sense-fe4145b4e305",
      "https://medium.com/p/38-actions-and-insights-to-become-a-better-software-architect-f135e2de9a1b",
      "https://medium.com/p/the-100-correct-way-to-structure-a-react-app-or-why-theres-no-such-thing-3ede534ef1ed",
      "https://medium.com/p/the-complete-illustrated-flexbox-tutorial-d35c085dbf35",
      "https://medium.com/p/how-to-add-push-notifications-to-a-web-app-with-firebase-528a702e13e1",
      "https://medium.com/p/push-notifications-and-real-time-notifications-in-web-application-89daeafbfe53",
      "https://medium.com/p/introduction-to-the-browser-push-and-notifications-api-44c512468d2b",
      "https://medium.com/p/5-ways-to-make-most-of-the-push-notifications-196515441af",
      "https://medium.com/p/website-push-notifications-implementation-explained-f19cd66c1017",
      "https://medium.com/p/firebase-cloud-notifications-on-web-with-react-and-redux-58a8b3a2a439",
      "https://medium.com/p/integrating-push-notifications-in-your-node-react-web-app-4e8d8190a52c",
      "https://medium.com/p/implementing-push-notifications-with-create-react-app-bf35cd25d870",
      "https://medium.com/p/using-firebase-to-provide-real-time-notifications-2f86b2f7d499",
      "https://medium.com/p/7-basic-rules-for-button-design-63dcdf5676b4",
      "https://medium.com/p/how-draft-js-represents-rich-text-data-eeabb5f25cf2",
      "https://medium.com/p/draft-js-update-editor-content-636d96e2c1a5",
      "https://medium.com/p/how-to-store-draft-js-content-75207f390b46",
      "https://medium.com/p/implementing-todo-list-in-draftjs-6a939bb81e32",
      "https://medium.com/p/draft-js-and-redux-the-perfect-couple-f5342503becd",
      "https://medium.com/p/draft-js-overview-with-code-snippets-56f740022854",
      "https://medium.com/p/draft-js-custom-block-rendering-c4221710323a",
      "https://medium.com/p/draft-js-editor-with-hashtags-and-mentions-part-1-9dd54485a2d3",
      "https://medium.com/p/best-practices-when-working-with-draft-js-81bd27e8aac3",
      "https://medium.com/p/draft-js-building-search-and-replace-functionality-688fd84f64cb",
      "https://medium.com/p/a-beginner-s-guide-to-draft-js-d1823f58d8cc",
      "https://medium.com/p/timsort-the-fastest-sorting-algorithm-youve-never-heard-of-36b28417f399",
      "https://medium.com/p/design-systems-at-github-c8e5378d2542",
      "https://medium.com/p/data-structures-linked-list-implementation-in-js-3beb48ff49cd",
      "https://medium.com/p/react-component-patterns-e7fb75be7bb0",
      "https://medium.com/p/microinteractions-detailed-design-9113c88946d0",
      "https://medium.com/p/3-practical-cheat-sheets-for-designing-attention-grabbing-uis-318e588bd864",
      "https://medium.com/p/better-ux-through-microinteractions-680cbe22b110",
      "https://medium.com/p/ux-digest-w9-2018-microinteractions-acb450e23276",
      "https://medium.com/p/microinteractions-a-walkthrough-bb8de322ddf7",
      "https://medium.com/p/micro-interactions-101-what-designers-need-to-know-13e7e297dd82",
      "https://medium.com/p/the-thinking-behind-micro-interaction-b6e9f7010491",
      "https://medium.com/p/micro-interactions-a-complete-beginners-guide-b446d90215ec",
      "https://medium.com/p/boost-your-design-by-micro-interactions-9fdb628e42ec",
      "https://medium.com/p/micro-interactions-why-when-and-how-to-use-them-to-boost-the-ux-17094b3baaa0",
      "https://medium.com/p/5-mistakes-to-avoid-when-designing-micro-interactions-a6f638ee6a86",
      "https://medium.com/p/u15-latest-and-best-loading-animations-to-make-user-enjoy-waiting-9c7861ed5d47",
      "https://medium.com/p/adding-a-robust-form-validation-to-react-redux-apps-616ca240c124",
      "https://medium.com/p/6-minute-beginners-guide-to-css-flexbox-527b3ff3480b",
      "https://medium.com/p/5-common-practices-that-you-can-stop-doing-in-react-9e866df5d269",
      "https://medium.com/p/its-time-to-remove-proptypes-and-just-use-flow-for-react-4a3de615aac5",
      "https://medium.com/p/javascript-async-await-the-good-part-pitfalls-and-how-to-use-9b759ca21cda",
      "https://medium.com/p/how-to-properly-structure-your-react-applications-5609ad3f2ee6",
      "https://medium.com/p/using-redux-observable-to-handle-asynchronous-logic-in-redux-d49194742522",
      "https://medium.com/p/how-to-use-react-createref-ea014ad09dba",
      "https://medium.com/p/how-to-develop-an-eye-for-design-c5a4c64bb26c",
      "https://medium.com/p/4-four-ways-to-style-react-components-ac6f323da822",
      "https://medium.com/p/top-10-es6-features-by-example-80ac878794bb",
      "https://medium.com/p/weekly-inspiration-for-designers-162-8433ff923bd",
      "https://medium.com/p/rest-vs-graphql-a-critical-review-5f77392658e7",
      "https://medium.com/p/how-to-build-a-range-slider-component-in-react-from-scratch-using-only-div-and-span-d53e1a62c4a3",
      "https://medium.com/p/the-difference-between-function-and-block-scope-in-javascript-4296b2322abe",
      "https://medium.com/p/javascript-es6-iterables-and-iterators-de18b54f4d4",
      "https://medium.com/p/what-are-the-best-practices-when-testing-rails-apps-1fcf0d7e7bf9",
      "https://medium.com/p/five-tips-for-working-with-redux-in-large-applications-89452af4fdcb",
      "https://medium.com/p/ui-interactions-of-the-week-133-bf8578b14459",
      "https://medium.com/p/learning-react-roadmap-from-scratch-to-advanced-bff7735531b6",
      "https://medium.com/p/you-learned-the-basics-of-react-now-what-389e69be3c5a",
      "https://medium.com/p/v4-create-react-redux-app-structure-with-build-configurations-whats-new-523bdec328c6",
      "https://medium.com/p/react-redux-tips-and-best-practices-for-clean-reliable-maintainable-code-4daa068e1a4d",
      "https://medium.com/p/learn-react-fundamentals-and-advanced-patterns-eac90341c9db",
      "https://medium.com/p/updated-advanced-react-component-patterns-51c34b44b1df",
      "https://medium.com/p/advanced-react-router-concepts-code-splitting-animated-transitions-scroll-restoration-recursive-17096c0cf9db",
      "https://medium.com/p/top-resources-to-explore-react-fiber-9a2b19114520",
      "https://medium.com/p/how-javascript-works-service-workers-their-life-cycle-and-use-cases-52b19ad98b58",
      "https://medium.com/p/how-javascript-works-the-building-blocks-of-web-workers-5-cases-when-you-should-use-them-a547c0757f6a",
      "https://medium.com/p/achieve-more-reactivity-with-web-workers-and-queues-dac461ec5f8e",
      "https://medium.com/p/using-web-workers-react-and-webpack-d2773e3f362d",
      "https://medium.com/p/introduction-to-service-workers-7fe055aad48d",
      "https://medium.com/p/running-fetch-in-a-web-worker-700dc33ac854",
      "https://medium.com/p/web-workers-to-the-rescue-4ecf4279953c",
      "https://medium.com/p/how-to-use-web-workers-with-react-create-app-and-not-ejecting-in-the-attempt-3718d2a1166b",
      "https://medium.com/p/creating-a-simple-chatroom-with-websockets-actioncable-759246c2d55d",
      "https://medium.com/p/rails-react-webpacker-actioncable-283c6ac86ddb",
      "https://medium.com/p/connect-an-autonomous-js-app-to-actioncable-for-realtime-goodness-5a76a05c7594",
      "https://medium.com/p/set-up-a-chat-app-backend-with-rails-action-cable-d60f0a6e63c1",
      "https://medium.com/p/bringing-beer-lovers-together-through-react-and-actioncable-d618a4a4a235",
      "https://medium.com/p/actioncable-authentication-in-a-token-based-rails-api-f9cc4b8bf560",
      "https://medium.com/p/how-to-use-rails-5-action-cable-to-build-a-chat-system-with-multiple-private-rooms-with-multiple-5bf82d98a5aa",
      "https://medium.com/p/how-to-setup-real-time-data-flow-with-action-cable-rails-and-react-js-5da0f46a402c",
      "https://medium.com/p/optimizing-react-app-performance-using-web-workers-79266afd4a7",
      "https://medium.com/p/how-web-workers-can-help-with-consistent-asynchronous-tasks-in-javascript-cd6d728fa4ee",
      "https://medium.com/p/what-are-web-sockets-what-about-rest-apis-b9c15fd72aac",
      "https://medium.com/p/how-to-build-a-chat-application-using-react-redux-redux-saga-and-web-sockets-47423e4bc21a",
      "https://medium.com/p/reactjs-ruby-on-rails-api-heroku-app-2645c93f0814",
      "https://medium.com/p/react-devtools-c2d56a901f37",
      "https://medium.com/p/build-a-desktop-chat-app-with-react-electron-and-chatkit-744d168e6f2f",
      "https://medium.com/p/when-and-why-you-should-use-es6-arrow-functions-and-when-you-shouldnt-3d851d7f0b26",
      "https://medium.com/p/ceiling-analysis-in-deep-learning-and-software-development-8bc41e59364a",
      "https://medium.com/p/user-centered-growth-design-97a53d829807",
      "https://medium.com/p/react-inline-functions-and-performance-bdff784f5578",
      "https://medium.com/p/declarative-routing-with-react-router-v4-7419c198e93f",
      "https://medium.com/p/why-you-should-use-simpler-redux-for-react-redux-development-375b9b0e3cff",
      "https://medium.com/p/database-stakeholder-display-of-design-research-results-aca7f6150525",
      "https://medium.com/p/the-importance-of-readable-code-165895e939c7",
      "https://medium.com/p/tips-on-react-for-large-scale-projects-3f9ece85983d",
      "https://medium.com/p/shape-your-redux-store-like-your-database-98faa4754fd5",
      "https://medium.com/p/ux-design-tools-for-2018-for-mac-and-pc-320a7be230c9",
      "https://medium.com/p/laying-the-foundation-rebuilding-articles-on-the-atlantic-90ae00263636",
      "https://medium.com/p/improving-performance-at-the-atlantic-3284aee4b9ea",
      "https://medium.com/p/do-more-with-less-using-render-props-de5bcdfbe74c",
      "https://medium.com/p/graphql-front-end-queries-made-easy-68e9d9ded283",
      "https://medium.com/p/10-javascript-concepts-you-need-to-know-for-interviews-136df65ecce",
      "https://medium.com/p/stack-overflow-2018-developer-survey-faac8d3eb357",
      "https://medium.com/p/create-a-beautiful-landing-page-animation-with-css-8f4501c20c8e",
      "https://medium.com/p/the-hash-table-51516f49f347",
      "https://medium.com/p/learn-these-javascript-fundamentals-and-become-a-better-developer-2a031a0dc9cf",
      "https://medium.com/p/frontend-in-the-backend-a-pattern-for-cleaner-code-b497c92d0b49",
      "https://medium.com/p/follow-these-steps-to-solve-any-dynamic-programming-interview-problem-cc98e508cd0e",
      "https://medium.com/p/higher-order-components-the-ultimate-guide-b453a68bb851",
      "https://medium.com/p/animated-transitions-with-react-router-a0ad00e633f1",
      "https://medium.com/p/a-comprehensive-guide-to-react-js-in-2018-ba8bb6975597",
      "https://medium.com/p/server-rendering-with-react-and-react-router-e0b7ba37653f",
      "https://medium.com/p/redesigning-redux-b2baee8b8a38",
      "https://medium.com/p/react-js-top-10-articles-for-the-past-month-v-apr-2018-e3cccab07012",
      "https://medium.com/p/introducing-the-graphql-guide-11a5ae48628a",
      "https://medium.com/p/complex-app-logic-with-redux-and-redux-saga-write-an-authentication-monitor-2f5672303d7d",
      "https://medium.com/p/when-to-use-control-props-or-state-reducers-6cd83e42c5b",
      "https://medium.com/p/testing-your-react-app-with-puppeteer-and-jest-c72b3dfcde59",
      "https://medium.com/p/introducing-the-single-element-pattern-dfbd2c295c5d",
      "https://medium.com/p/understanding-redux-the-worlds-easiest-guide-to-beginning-redux-c695f45546f6",
      "https://medium.com/p/17-interactive-site-designs-youll-want-to-steal-30a5bd6d500c",
      "https://medium.com/p/css-grid-vs-flexbox-building-simple-layouts-43e569a66f0a",
      "https://medium.com/p/how-to-use-visual-cues-in-web-design-a23febee9039",
      "https://medium.com/p/understanding-basic-concepts-of-css-flexbox-ffa657dc39c1",
      "https://medium.com/p/learn-javascript-es-2017-string-padding-padstart-padend-88e90783e7de",
      "https://medium.com/p/how-to-build-a-simple-blog-using-react-and-graphql-4a680b6e3206",
      "https://medium.com/p/the-ui-and-ux-design-pocket-guide-volume-one-dfb3675ea828",
      "https://medium.com/p/harnessing-the-power-of-react-in-design-prototyping-4a74e70db5f5",
      "https://medium.com/p/atomic-design-with-react-e7aea8152957",
      "https://medium.com/p/how-to-write-better-code-in-react-best-practices-b8ca87d462b0",
      "https://medium.com/p/11-react-component-libraries-you-should-know-178eb1dd6aa4",
      "https://medium.com/p/atomic-components-managing-dynamic-react-components-using-atomic-design-part-1-5f07451f261f",
      "https://medium.com/p/evolving-patterns-in-react-116140e5fe8f",
      "https://medium.com/p/moving-form-redux-thunk-to-redux-saga-5c19d0011ca0",
      "https://medium.com/p/painless-end-to-end-testing-using-puppeteer-and-jest-11325e81fb6d",
      "https://medium.com/p/jest-react-and-preact-1ae20847ba92",
      "https://medium.com/p/unit-testing-redux-actions-reducers-and-epics-with-jest-484f8a59f1f2",
      "https://medium.com/p/tools-of-the-trade-react-testing-with-enzyme-and-jest-c70ba40f69a9",
      "https://medium.com/p/reasons-to-love-jest-the-developer-experience-b00ec93df7bb",
      "https://medium.com/p/javascript-quality-control-with-jest-and-eslint-b888eeb4b0c4",
      "https://medium.com/p/implementing-basic-component-tests-using-jest-and-enzyme-d1d8788d627a",
      "https://medium.com/p/applying-microservices-design-patterns-to-scale-react-app-development-2c1f9df88452",
      "https://medium.com/p/ultimate-react-component-patterns-with-typescript-2-8-82990c516935",
      "https://medium.com/p/using-advanced-design-patterns-to-create-flexible-and-reusable-react-components-part-2-react-3c5662b997ab",
      "https://medium.com/p/using-advanced-design-patterns-to-create-flexible-and-reusable-react-components-part-3-render-d7517dfe72bc",
      "https://medium.com/p/how-to-use-redux-on-highly-scalable-javascript-applications-4e4b8cb5ef38",
      "https://medium.com/p/simplify-complex-ui-by-implementing-the-atomic-design-in-react-with-bit-f4ad116ec8db",
      "https://medium.com/p/growth-engineering-at-netflix-accelerating-innovation-90eb8e70ce59",
      "https://medium.com/p/how-to-use-the-new-react-context-api-fce011e7d87",
      "https://medium.com/p/useful-javascript-array-and-object-methods-6c7971d93230",
      "https://medium.com/p/11-javascript-utility-libraries-you-should-know-in-2018-3646fb31ade",
      "https://medium.com/p/javascript-function-declaration-vs-expression-f5873b8c7b38",
      "https://medium.com/p/javascript-es-2017-learn-object-keys-object-values-and-object-entries-2626682f9667",
      "https://medium.com/p/7-javascript-methods-that-will-boost-your-skills-in-less-than-8-minutes-4cc4c3dca03f",
      "https://medium.com/p/some-of-javascripts-most-useful-features-can-be-tricky-let-me-explain-them-4003d7bbed32",
      "https://medium.com/p/react-context-api-a-replacement-for-redux-6e20790492b3",
      "https://medium.com/p/javascript-code-cleanup-how-you-can-refactor-to-use-classes-3948118e4468",
      "https://medium.com/p/draft-js-editor-with-hashtags-and-mentions-part-2-4986c119eca2",
      "https://medium.com/p/how-to-better-organize-your-react-applications-2fd3ea1920f1",
      "https://medium.com/p/react-component-patterns-ab1f09be2c82",
      "https://medium.com/p/how-to-build-a-react-js-chat-app-in-10-minutes-c9233794642b",
      "https://medium.com/p/putting-a-draft-js-wysiwyg-editor-into-your-react-project-8f82493a742",
      "https://medium.com/p/how-to-display-draft-js-content-as-html-154a0b2bac27",
      "https://medium.com/p/seeing-through-redux-with-lenses-112ecb250f4",
      "https://medium.com/p/yes-react-is-taking-over-front-end-development-the-question-is-why-40837af8ab76",
      "https://medium.com/p/the-new-york-times-now-on-apollo-b9a78a5038c",
      "https://medium.com/p/how-to-write-medium-stories-people-will-actually-read-92e58a27c8d8",
      "https://medium.com/p/how-to-test-api-authentication-in-rails-2804fd31a1ea",
      "https://medium.com/p/build-awesome-forms-in-react-using-redux-form-d1e4c96f5850",
      "https://medium.com/p/10-tips-for-better-redux-architecture-69250425af44",
      "https://medium.com/p/what-medium-readers-are-hungry-for-df96ef92b289",
      "https://medium.com/p/how-to-grow-your-audience-on-medium-307f879a3468",
      "https://medium.com/p/the-art-and-science-of-tags-f3d0706949b0",
      "https://medium.com/p/expanding-the-medium-partner-program-3be09dd146e4",
      "https://medium.com/p/the-medium-model-3ec28c6f603a",
      "https://medium.com/p/a-guide-to-technical-interviews-at-medium-49850139aa03",
      "https://medium.com/p/2-fast-2-furious-migrating-mediums-codebase-without-slowing-down-84b1e33d81f4",
      "https://medium.com/p/engineering-interviews-what-we-screen-for-af2d84122417",
      "https://medium.com/p/engineering-interviews-refining-our-process-52fbc9510e91",
      "https://medium.com/p/engineering-growth-frequently-asked-questions-e860b07ca4ab",
      "https://medium.com/p/engineering-growth-appeals-process-25a2161ed582",
      "https://medium.com/p/engineering-growth-assessing-progress-743620e70763",
      "https://medium.com/p/engineering-growth-tracks-b1fad620787e",
      "https://medium.com/p/engineering-growth-introduction-8ba7b78c8d6c",
      "https://medium.com/p/engineering-growth-framework-overview-4e02ab330524",
      "https://medium.com/p/mapping-mediums-tags-1b9a78d77cf0",
      "https://medium.com/p/when-to-use-component-or-purecomponent-a60cfad01a81",
      "https://medium.com/p/a-basic-react-redux-introductory-tutorial-adcc681eeb5e",
      "https://medium.com/p/react-native-and-redux-part-1-754c13a440ba",
      "https://medium.com/p/getting-started-with-react-redux-1baae4dcb99b",
      "https://medium.com/p/redux-vs-react-context-87a7053c12df",
      "https://medium.com/p/github-glitch-and-the-future-of-social-coding-5e6faa45c8f2",
      "https://medium.com/p/rendering-large-lists-with-react-virtualized-82741907a6b3",
      "https://medium.com/p/fractal-a-react-app-structure-for-infinite-scale-4dab943092af",
      "https://medium.com/p/mindset-lessons-from-a-year-with-react-1de862421981",
      "https://medium.com/p/render-props-in-react-6081b6fa3593",
      "https://medium.com/p/build-a-chat-app-with-sentiment-analysis-using-next-js-c43ebf3ea643",
      "https://medium.com/p/7-rules-for-creating-gorgeous-ui-part-1-559d4e805cda",
      "https://medium.com/p/5-tools-for-faster-development-in-react-676f134050f2",
      "https://medium.com/p/functional-setstate-is-the-future-of-react-374f30401b6b",
      "https://medium.com/p/working-with-paginated-api-in-redux-be871818e444",
      "https://medium.com/p/these-four-clean-code-tips-will-dramatically-improve-your-engineering-teams-productivity-b5bd121dd150",
      "https://medium.com/p/building-a-text-editor-for-a-digital-first-newsroom-f1cb8367fc21",
      "https://medium.com/p/front-end-architecture-part-1-file-structure-74bc2806fc4",
      "https://medium.com/p/advanced-react-component-patterns-56af2b74bc5f",
      "https://medium.com/p/using-reactjs-hoc-pattern-be-aware-of-the-side-effects-f52beae77703",
      "https://medium.com/p/web-scraping-in-javascript-with-nanopipe-bb0ac5bc5560",
      "https://medium.com/p/creating-a-pattern-for-the-new-react-context-api-ce87653e50b3",
      "https://medium.com/p/the-tech-interview-cheatsheet-8e28d94f5f04",
      "https://medium.com/p/visually-testing-react-components-using-the-eyes-storybook-sdk-33384a51f05e",
      "https://medium.com/p/implement-linear-and-binary-search-algorithms-with-javascript-2149997588f0",
      "https://medium.com/p/cracking-the-front-end-developer-interview-part-1-be3619b60cc4",
      "https://medium.com/p/top-10-web-design-trends-to-follow-in-2018-79623d6ff3d2",
      "https://medium.com/p/using-a-datepicker-in-react-js-b67e970195fd",
      "https://medium.com/p/what-can-react-context-api-do-for-you-multi-language-text-modals-and-theme-switchers-9cfbc8e5ee5e",
      "https://medium.com/p/learning-react-js-by-building-a-minesweeper-game-ced9d41560ed",
      "https://medium.com/p/javascript-questions-to-ask-in-technical-interviews-fullstack-frontend-backend-84fec4db4c44",
      "https://medium.com/p/basic-ecmascript-6-interview-questions-and-answers-e6e9f9b3ff2d",
      "https://medium.com/p/understanding-react-react-16-3-component-life-cycle-23129bc7a705",
      "https://medium.com/p/how-to-create-a-react-component-and-publish-it-in-npm-668ad7d363ce",
      "https://medium.com/p/unit-testing-redux-connected-components-692fa3c4441c",
      "https://medium.com/p/css-grid-responsive-layouts-and-components-eee1badd5a2f",
      "https://medium.com/p/handling-race-conditions-with-redux-thunk-c348a7a5a839",
      "https://medium.com/p/the-react-state-museum-a278c726315",
      "https://medium.com/p/react-patterns-you-should-know-da86568372fa",
      "https://medium.com/p/ivy-league-free-online-courses-a0d7ae675869"]
    end

    def seed_db
      all_links.each do |link|
        doc = Nokogiri::HTML(open(link))
        if doc
          a = Article.find_or_create_by(title: doc.css("h1").inner_text, content: doc.css("div.sectionLayout--insetColumn").inner_html)

            if doc.search('time').find{ |time| time.attributes }
              if doc.search('time').find{ |time| time.attributes.include?('datetime') }.attributes["datetime"].value
                a.update(date: doc.search('time').find{ |time| time.attributes.include?('datetime') }.attributes["datetime"].value)
              end
            end

        end


        tags = doc.css('ul.tags li').map { |tag| tag.inner_text }
        tags.each do |tag|
          t = Tag.find_or_create_by(name: tag)
          a.tags << t
        end
      end
    end


  # def print_first_title
  #   first_page = @all_links[0]
  #   Nokogiri::HTML(open(first_page)).css("h1").inner_text
  # end
  #
  # def print_first_date
  #   first_page = @all_links[0]
  #   doc = Nokogiri::HTML(open(first_page))
  #   doc.search('time').find{ |time| time.attributes.include?('datetime') }.attributes["datetime"].value
  # end
  #
  # def print_first_uri
  #   first_page = @all_links[0]
  #   Nokogiri::HTML(open(first_page)).css("div.sectionLayout--insetColumn").inner_html
  # end
  #
  # def print_first_tags
  #   first_page = @all_links[0]
  #   all_tags = []
  #   all_tags = all_tags.concat(Nokogiri::HTML(open(first_page)).css('ul.tags li').map { |tag| tag.inner_text })
  #   all_tags
  # end

  def run
    all_links
    seed_db
    puts Article.all.length
  end

end

Scraper.new.run


# [page_1, page_2, page_3, page_4, page_5].map do |page|
#    all_links.concat(Nokogiri::HTML(page).css("a.h-cite").map { |link| link['href'] })
# end
#
# first_page = all_links[0]
#
# Nokogiri::HTML(open(first_page)).css("div.section-inner .sectionLayout--insetColumn")
#
# all_links.length

# doc_1 = Nokogiri::HTML(page_1)
